query PlaybackSyncInterval($Key: String!) {
  AppSettings: appSettings(
    where: { Key: { eq: $Key } }
    page: { limit: 1, offset: 0 }
  ) {
    Edges: edges {
      Node: node {
        Id
        Key
        Value
      }
    }
  }
}

query TorrentAppSettings {
  AppSettings: appSettings(
    where: { Category: { eq: "torrent" } }
    page: { limit: 20, offset: 0 }
  ) {
    Edges: edges {
      Node: node {
        Id
        Key
        Value
      }
    }
  }
}

query MetadataAppSettings {
  AppSettings: appSettings(
    where: { Category: { eq: "metadata" } }
    page: { limit: 50, offset: 0 }
  ) {
    Edges: edges {
      Node: node {
        Id
        Key
        Value
      }
    }
  }
}

query LlmAppSettings {
  AppSettings: appSettings(
    where: { Category: { eq: "llm" } }
    page: { limit: 100, offset: 0 }
  ) {
    Edges: edges {
      Node: node {
        Id
        Key
        Value
      }
    }
  }
}

mutation CreateAppSetting($Input: CreateAppSettingInput!) {
  CreateAppSetting: createAppSetting(input: $Input) {
    Success: success
    Error: error
    AppSetting: appSetting {
      Id
      Key
      Value
    }
  }
}

mutation UpdateAppSetting($Id: String!, $Input: UpdateAppSettingInput!) {
  UpdateAppSetting: updateAppSetting(id: $Id, input: $Input) {
    Success: success
    Error: error
    AppSetting: appSetting {
      Id
      Key
      Value
    }
  }
}
