query NeedsSetup {
  needsSetup
}

query Me {
  me {
    id
    email
    username
    role
    displayName
  }
}

mutation Login($input: LoginInput!) {
  login(input: $input) {
    success
    error
    user {
      id
      email
      username
      role
      displayName
    }
    tokens {
      expiresIn
      tokenType
    }
  }
}

mutation Register($input: RegisterUserInput!) {
  register(input: $input) {
    success
    error
    user {
      id
      email
      username
      role
      displayName
    }
    tokens {
      expiresIn
      tokenType
    }
  }
}

mutation RefreshToken {
  refreshToken {
    success
    error
    tokens {
      expiresIn
      tokenType
    }
  }
}

mutation Logout {
  logout {
    success
    error
  }
}
