query NeedsSetup {
  NeedsSetup
}

query Me {
  Me {
    Id
    Email
    Username
    Role
    DisplayName
  }
}

mutation Login($input: LoginInput!) {
  Login(Input: $input) {
    Success
    Error
    User {
      Id: id
      Email: email
      Username: username
      Role: role
      DisplayName: displayName
    }
    Tokens {
      AccessToken: accessToken
      RefreshToken: refreshToken
      ExpiresIn: expiresIn
      TokenType: tokenType
    }
  }
}

mutation Register($input: RegisterUserInput!) {
  Register(Input: $input) {
    Success
    Error
    User {
      Id: id
      Email: email
      Username: username
      Role: role
      DisplayName: displayName
    }
    Tokens {
      AccessToken: accessToken
      RefreshToken: refreshToken
      ExpiresIn: expiresIn
      TokenType: tokenType
    }
  }
}

mutation RefreshToken($input: RefreshTokenInput!) {
  RefreshToken(Input: $input) {
    Success
    Error
    Tokens {
      AccessToken: accessToken
      RefreshToken: refreshToken
      ExpiresIn: expiresIn
      TokenType: tokenType
    }
  }
}

mutation Logout($input: LogoutInput!) {
  Logout(Input: $input) {
    Success
    Error
  }
}
