query CollectionDetailRoute($id: String!) {
  collection(id: $id) {
    id
    libraryId
    tmdbCollectionId
    name
    overview
    posterUrl
    backdropUrl
    movieCount
  }
}

query CollectionDetailResolveByTmdbRoute(
  $where: CollectionWhereInput
  $page: PageInput
) {
  collections(where: $where, page: $page) {
    edges {
      node {
        id
        libraryId
        tmdbCollectionId
        name
        overview
        posterUrl
        backdropUrl
        movieCount
      }
    }
  }
}

query CollectionDetailLibraryRoute($id: String!) {
  library(id: $id) {
    id
    name
  }
}

query CollectionDetailMoviesRoute($libraryId: String!, $collectionId: Int!) {
  movieCollectionDetails(libraryId: $libraryId, collectionId: $collectionId) {
    collectionId
    name
    movies {
      tmdbId
      title
      year
      posterUrl
      libraryMovieId
      mediaFileId
      fileSizeBytes
      resolution
      videoCodec
      audioCodec
      audioChannels
      wanted
    }
  }
}
