query DashboardShows(
  $Where: ShowWhereInput
  $Page: PageInput
  $OrderBy: [ShowOrderByInput!]
) {
  Shows: shows(where: $Where, page: $Page, orderBy: $OrderBy) {
    Edges: edges {
      Node: node {
        Id
        LibraryId
        Name
        SortName
        Year
        TvmazeId
        TmdbId
        TvdbId
        ImdbId
        Overview
        Network
        Runtime
        PosterUrl
        BackdropUrl
        Path
        Genres
        CreatedAt
      }
      Cursor: cursor
    }
    PageInfo: pageInfo {
      TotalCount: totalCount
    }
  }
}

query DashboardScheduleCaches(
  $Where: ScheduleCacheWhereInput
  $OrderBy: [ScheduleCacheOrderByInput!]
  $Page: PageInput
) {
  ScheduleCaches: scheduleCaches(
    where: $Where
    orderBy: $OrderBy
    page: $Page
  ) {
    Edges: edges {
      Node: node {
        Id
        TvmazeEpisodeId
        EpisodeName
        Season
        EpisodeNumber
        EpisodeType
        AirDate
        AirTime
        AirStamp
        Runtime
        EpisodeImageUrl
        Summary
        TvmazeShowId
        ShowName
        ShowNetwork
        ShowPosterUrl
        ShowGenres
        CountryCode
      }
      Cursor: cursor
    }
    PageInfo: pageInfo {
      TotalCount: totalCount
    }
  }
}
