query AppLogs(
  $where: AppLogWhereInput
  $orderBy: [AppLogOrderByInput!]
  $page: PageInput
) {
  appLogs(where: $where, orderBy: $orderBy, page: $page) {
    edges {
      node {
        id
        timestamp
        level
        target
        message
        fields
        spanName
      }
      cursor
    }
    pageInfo {
      hasNextPage
      totalCount
    }
  }
}

subscription AppLogChanged($filter: SubscriptionFilterInput) {
  appLogChanged(filter: $filter) {
    action
    id
    appLog {
      id
      timestamp
      level
      target
      message
      fields
      spanName
    }
  }
}

mutation DeleteAppLogs($where: AppLogWhereInput!) {
  deleteAppLogs(where: $where) {
    success
    error
    deletedCount
  }
}
