query AppLogs(
  $Where: AppLogWhereInput
  $OrderBy: [AppLogOrderByInput!]
  $Page: PageInput
) {
  AppLogs: appLogs(where: $Where, orderBy: $OrderBy, page: $Page) {
    Edges: edges {
      Node: node {
        Id
        Timestamp
        Level
        Target
        Message
        Fields
        SpanName
      }
      Cursor: cursor
    }
    PageInfo: pageInfo {
      HasNextPage: hasNextPage
      TotalCount: totalCount
    }
  }
}

subscription AppLogChanged($Filter: SubscriptionFilterInput) {
  AppLogChanged: appLogChanged(filter: $Filter) {
    Action: action
    Id: id
    AppLog: appLog {
      Id
      Timestamp
      Level
      Target
      Message
      Fields
      SpanName
    }
  }
}

mutation DeleteAppLogs($Where: AppLogWhereInput!) {
  DeleteAppLogs: deleteAppLogs(where: $Where) {
    success
    error
    DeletedCount: deletedCount
  }
}
