query OrganizationNamingPatterns(
  $orderBy: [NamingPatternOrderByInput!]
  $page: PageInput
) {
  namingPatterns(orderBy: $orderBy, page: $page) {
    edges {
      node {
        id
        name
        pattern
        description
        libraryType
        isDefault
        isSystem
      }
    }
  }
}

mutation OrganizationCreateNamingPattern($input: CreateNamingPatternInput!) {
  createNamingPattern(input: $input) {
    success
    error
    namingPattern {
      id
      name
      pattern
      description
      libraryType
      isDefault
      isSystem
    }
  }
}

mutation OrganizationUpdateNamingPattern(
  $id: String!
  $input: UpdateNamingPatternInput!
) {
  updateNamingPattern(id: $id, input: $input) {
    success
    error
    namingPattern {
      id
      name
      pattern
      description
      libraryType
      isDefault
      isSystem
    }
  }
}

mutation OrganizationDeleteNamingPattern($id: String!) {
  deleteNamingPattern(id: $id) {
    success
    error
  }
}
