query Notifications(
  $Where: NotificationWhereInput
  $OrderBy: [NotificationOrderByInput!]
  $Page: PageInput
) {
  Notifications: notifications(where: $Where, orderBy: $OrderBy, page: $Page) {
    Edges: edges {
      Node: node {
        Id
        UserId
        NotificationType
        Category
        Title
        Message
        LibraryId
        TorrentId
        MediaFileId
        PendingMatchId
        ActionType
        ActionData
        ReadAt
        ResolvedAt
        Resolution
        CreatedAt
        UpdatedAt
      }
      Cursor: cursor
    }
    PageInfo: pageInfo {
      HasNextPage: hasNextPage
      TotalCount: totalCount
    }
  }
}

subscription NotificationChanged($Filter: SubscriptionFilterInput) {
  NotificationChanged: notificationChanged(filter: $Filter) {
    Action: action
    Id: id
    Notification: notification {
      Id
      ReadAt
      ResolvedAt
      Resolution
    }
  }
}

mutation UpdateNotification($Id: String!, $Input: UpdateNotificationInput!) {
  UpdateNotification: updateNotification(id: $Id, input: $Input) {
    Success: success
    Error: error
    Notification: notification {
      Id
      ReadAt
      ResolvedAt
      Resolution
    }
  }
}

mutation DeleteNotification($Id: String!) {
  DeleteNotification: deleteNotification(id: $Id) {
    Success: success
    Error: error
  }
}
