query SearchTvShows($Query: String!) {
  SearchTvShows(Query: $Query) {
    Provider
    ProviderId
    Name
    Year
    Network
    Overview
    Status
    PosterUrl
    TvdbId
    ImdbId
    Score
  }
}

mutation AddTvShow($LibraryId: String!, $Input: AddTvShowInput!) {
  AddTvShow(LibraryId: $LibraryId, Input: $Input) {
    Success
    Show {
      Id
      Name
    }
    Error
  }
}

subscription ShowChanged($Filter: SubscriptionFilterInput) {
  ShowChanged: showChanged(filter: $Filter) {
    Action: action
    Id: id
    Show: show {
      LibraryId
    }
  }
}

query ShowDetailRoute($Id: String!) {
  Show: show(id: $Id) {
    Id
    LibraryId
    Name
    SortName
    Year
    TvmazeId
    TmdbId
    TvdbId
    ImdbId
    Overview
    Network
    PosterUrl
    BackdropUrl
    Runtime
    Genres
    AutoDownload
    AutoDownloadMode
    Path
    CreatedAt
    UpdatedAt
    UserId
    Episodes: episodes(page: { limit: 2000 }) {
      Edges: edges {
        Node: node {
          Id
          ShowId
          Season
          Episode
          AbsoluteNumber
          Title
          Overview
          AirDate
          Runtime
          TvmazeId
          TmdbId
          TvdbId
          MediaFileId
          Wanted
          MediaFile: mediaFile {
            Id
            Size
            Duration
            Resolution
            VideoCodec
            AudioCodec
            AudioChannels
            IsHdr
            HdrType
          }
          CreatedAt
          UpdatedAt
        }
      }
    }
  }
}

mutation RefreshShowRoute($Id: String!) {
  RefreshShow(Id: $Id) {
    Success
    Show {
      Id
      Name
      Overview
    }
    Error
  }
}

mutation ShowDetailSetEpisodeWanted($ShowId: String!, $Wanted: Boolean!) {
  UpdateEpisodes: updateEpisodes(
    where: { ShowId: { eq: $ShowId } }
    input: { Wanted: $Wanted }
  ) {
    success
    error
    affectedCount
  }
}
