/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SubscriptionsIndexRouteImport } from './routes/subscriptions/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as LibrariesIndexRouteImport } from './routes/libraries/index'
import { Route as DownloadsIndexRouteImport } from './routes/downloads/index'
import { Route as ShowsShowIdRouteImport } from './routes/shows/$showId'
import { Route as SettingsMetadataRouteImport } from './routes/settings/metadata'
import { Route as LibraryMediaIdRouteImport } from './routes/library/$mediaId'
import { Route as LibrariesLibraryIdRouteImport } from './routes/libraries/$libraryId'
import { Route as AuthLoginRouteImport } from './routes/auth/login'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscriptionsIndexRoute = SubscriptionsIndexRouteImport.update({
  id: '/subscriptions/',
  path: '/subscriptions/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const LibrariesIndexRoute = LibrariesIndexRouteImport.update({
  id: '/libraries/',
  path: '/libraries/',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadsIndexRoute = DownloadsIndexRouteImport.update({
  id: '/downloads/',
  path: '/downloads/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShowsShowIdRoute = ShowsShowIdRouteImport.update({
  id: '/shows/$showId',
  path: '/shows/$showId',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsMetadataRoute = SettingsMetadataRouteImport.update({
  id: '/settings/metadata',
  path: '/settings/metadata',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryMediaIdRoute = LibraryMediaIdRouteImport.update({
  id: '/library/$mediaId',
  path: '/library/$mediaId',
  getParentRoute: () => rootRouteImport,
} as any)
const LibrariesLibraryIdRoute = LibrariesLibraryIdRouteImport.update({
  id: '/libraries/$libraryId',
  path: '/libraries/$libraryId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth/login': typeof AuthLoginRoute
  '/libraries/$libraryId': typeof LibrariesLibraryIdRoute
  '/library/$mediaId': typeof LibraryMediaIdRoute
  '/settings/metadata': typeof SettingsMetadataRoute
  '/shows/$showId': typeof ShowsShowIdRoute
  '/downloads': typeof DownloadsIndexRoute
  '/libraries': typeof LibrariesIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/subscriptions': typeof SubscriptionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/login': typeof AuthLoginRoute
  '/libraries/$libraryId': typeof LibrariesLibraryIdRoute
  '/library/$mediaId': typeof LibraryMediaIdRoute
  '/settings/metadata': typeof SettingsMetadataRoute
  '/shows/$showId': typeof ShowsShowIdRoute
  '/downloads': typeof DownloadsIndexRoute
  '/libraries': typeof LibrariesIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/subscriptions': typeof SubscriptionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth/login': typeof AuthLoginRoute
  '/libraries/$libraryId': typeof LibrariesLibraryIdRoute
  '/library/$mediaId': typeof LibraryMediaIdRoute
  '/settings/metadata': typeof SettingsMetadataRoute
  '/shows/$showId': typeof ShowsShowIdRoute
  '/downloads/': typeof DownloadsIndexRoute
  '/libraries/': typeof LibrariesIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/subscriptions/': typeof SubscriptionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth/login'
    | '/libraries/$libraryId'
    | '/library/$mediaId'
    | '/settings/metadata'
    | '/shows/$showId'
    | '/downloads'
    | '/libraries'
    | '/settings'
    | '/subscriptions'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/login'
    | '/libraries/$libraryId'
    | '/library/$mediaId'
    | '/settings/metadata'
    | '/shows/$showId'
    | '/downloads'
    | '/libraries'
    | '/settings'
    | '/subscriptions'
  id:
    | '__root__'
    | '/'
    | '/auth/login'
    | '/libraries/$libraryId'
    | '/library/$mediaId'
    | '/settings/metadata'
    | '/shows/$showId'
    | '/downloads/'
    | '/libraries/'
    | '/settings/'
    | '/subscriptions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthLoginRoute: typeof AuthLoginRoute
  LibrariesLibraryIdRoute: typeof LibrariesLibraryIdRoute
  LibraryMediaIdRoute: typeof LibraryMediaIdRoute
  SettingsMetadataRoute: typeof SettingsMetadataRoute
  ShowsShowIdRoute: typeof ShowsShowIdRoute
  DownloadsIndexRoute: typeof DownloadsIndexRoute
  LibrariesIndexRoute: typeof LibrariesIndexRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
  SubscriptionsIndexRoute: typeof SubscriptionsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscriptions/': {
      id: '/subscriptions/'
      path: '/subscriptions'
      fullPath: '/subscriptions'
      preLoaderRoute: typeof SubscriptionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/libraries/': {
      id: '/libraries/'
      path: '/libraries'
      fullPath: '/libraries'
      preLoaderRoute: typeof LibrariesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/downloads/': {
      id: '/downloads/'
      path: '/downloads'
      fullPath: '/downloads'
      preLoaderRoute: typeof DownloadsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shows/$showId': {
      id: '/shows/$showId'
      path: '/shows/$showId'
      fullPath: '/shows/$showId'
      preLoaderRoute: typeof ShowsShowIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/metadata': {
      id: '/settings/metadata'
      path: '/settings/metadata'
      fullPath: '/settings/metadata'
      preLoaderRoute: typeof SettingsMetadataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library/$mediaId': {
      id: '/library/$mediaId'
      path: '/library/$mediaId'
      fullPath: '/library/$mediaId'
      preLoaderRoute: typeof LibraryMediaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/libraries/$libraryId': {
      id: '/libraries/$libraryId'
      path: '/libraries/$libraryId'
      fullPath: '/libraries/$libraryId'
      preLoaderRoute: typeof LibrariesLibraryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthLoginRoute: AuthLoginRoute,
  LibrariesLibraryIdRoute: LibrariesLibraryIdRoute,
  LibraryMediaIdRoute: LibraryMediaIdRoute,
  SettingsMetadataRoute: SettingsMetadataRoute,
  ShowsShowIdRoute: ShowsShowIdRoute,
  DownloadsIndexRoute: DownloadsIndexRoute,
  LibrariesIndexRoute: LibrariesIndexRoute,
  SettingsIndexRoute: SettingsIndexRoute,
  SubscriptionsIndexRoute: SubscriptionsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
