/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SearchRouteImport } from './routes/search'
import { Route as HuntRouteImport } from './routes/hunt'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as LibrariesIndexRouteImport } from './routes/libraries/index'
import { Route as DownloadsIndexRouteImport } from './routes/downloads/index'
import { Route as ShowsShowIdRouteImport } from './routes/shows/$showId'
import { Route as SettingsUsenetRouteImport } from './routes/settings/usenet'
import { Route as SettingsTorrentRouteImport } from './routes/settings/torrent'
import { Route as SettingsSourcePrioritiesRouteImport } from './routes/settings/source-priorities'
import { Route as SettingsRssRouteImport } from './routes/settings/rss'
import { Route as SettingsParserRouteImport } from './routes/settings/parser'
import { Route as SettingsOrganizationRouteImport } from './routes/settings/organization'
import { Route as SettingsMetadataRouteImport } from './routes/settings/metadata'
import { Route as SettingsLogsRouteImport } from './routes/settings/logs'
import { Route as SettingsIndexersRouteImport } from './routes/settings/indexers'
import { Route as SettingsCastingRouteImport } from './routes/settings/casting'
import { Route as MoviesMovieIdRouteImport } from './routes/movies/$movieId'
import { Route as LibrariesLibraryIdRouteImport } from './routes/libraries/$libraryId'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AlbumsAlbumIdRouteImport } from './routes/albums/$albumId'
import { Route as LibrariesLibraryIdIndexRouteImport } from './routes/libraries/$libraryId/index'
import { Route as LibrariesLibraryIdUnmatchedRouteImport } from './routes/libraries/$libraryId/unmatched'
import { Route as LibrariesLibraryIdTracksRouteImport } from './routes/libraries/$libraryId/tracks'
import { Route as LibrariesLibraryIdShowsRouteImport } from './routes/libraries/$libraryId/shows'
import { Route as LibrariesLibraryIdSettingsRouteImport } from './routes/libraries/$libraryId/settings'
import { Route as LibrariesLibraryIdMoviesRouteImport } from './routes/libraries/$libraryId/movies'
import { Route as LibrariesLibraryIdCollectionsRouteImport } from './routes/libraries/$libraryId/collections'
import { Route as LibrariesLibraryIdBrowserRouteImport } from './routes/libraries/$libraryId/browser'
import { Route as LibrariesLibraryIdBooksRouteImport } from './routes/libraries/$libraryId/books'
import { Route as LibrariesLibraryIdAuthorsRouteImport } from './routes/libraries/$libraryId/authors'
import { Route as LibrariesLibraryIdArtistsRouteImport } from './routes/libraries/$libraryId/artists'
import { Route as LibrariesLibraryIdAlbumsRouteImport } from './routes/libraries/$libraryId/albums'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const HuntRoute = HuntRouteImport.update({
  id: '/hunt',
  path: '/hunt',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRoute,
} as any)
const LibrariesIndexRoute = LibrariesIndexRouteImport.update({
  id: '/libraries/',
  path: '/libraries/',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadsIndexRoute = DownloadsIndexRouteImport.update({
  id: '/downloads/',
  path: '/downloads/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShowsShowIdRoute = ShowsShowIdRouteImport.update({
  id: '/shows/$showId',
  path: '/shows/$showId',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsUsenetRoute = SettingsUsenetRouteImport.update({
  id: '/usenet',
  path: '/usenet',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsTorrentRoute = SettingsTorrentRouteImport.update({
  id: '/torrent',
  path: '/torrent',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsSourcePrioritiesRoute =
  SettingsSourcePrioritiesRouteImport.update({
    id: '/source-priorities',
    path: '/source-priorities',
    getParentRoute: () => SettingsRoute,
  } as any)
const SettingsRssRoute = SettingsRssRouteImport.update({
  id: '/rss',
  path: '/rss',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsParserRoute = SettingsParserRouteImport.update({
  id: '/parser',
  path: '/parser',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsOrganizationRoute = SettingsOrganizationRouteImport.update({
  id: '/organization',
  path: '/organization',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsMetadataRoute = SettingsMetadataRouteImport.update({
  id: '/metadata',
  path: '/metadata',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsLogsRoute = SettingsLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsIndexersRoute = SettingsIndexersRouteImport.update({
  id: '/indexers',
  path: '/indexers',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsCastingRoute = SettingsCastingRouteImport.update({
  id: '/casting',
  path: '/casting',
  getParentRoute: () => SettingsRoute,
} as any)
const MoviesMovieIdRoute = MoviesMovieIdRouteImport.update({
  id: '/movies/$movieId',
  path: '/movies/$movieId',
  getParentRoute: () => rootRouteImport,
} as any)
const LibrariesLibraryIdRoute = LibrariesLibraryIdRouteImport.update({
  id: '/libraries/$libraryId',
  path: '/libraries/$libraryId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AlbumsAlbumIdRoute = AlbumsAlbumIdRouteImport.update({
  id: '/albums/$albumId',
  path: '/albums/$albumId',
  getParentRoute: () => rootRouteImport,
} as any)
const LibrariesLibraryIdIndexRoute = LibrariesLibraryIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LibrariesLibraryIdRoute,
} as any)
const LibrariesLibraryIdUnmatchedRoute =
  LibrariesLibraryIdUnmatchedRouteImport.update({
    id: '/unmatched',
    path: '/unmatched',
    getParentRoute: () => LibrariesLibraryIdRoute,
  } as any)
const LibrariesLibraryIdTracksRoute =
  LibrariesLibraryIdTracksRouteImport.update({
    id: '/tracks',
    path: '/tracks',
    getParentRoute: () => LibrariesLibraryIdRoute,
  } as any)
const LibrariesLibraryIdShowsRoute = LibrariesLibraryIdShowsRouteImport.update({
  id: '/shows',
  path: '/shows',
  getParentRoute: () => LibrariesLibraryIdRoute,
} as any)
const LibrariesLibraryIdSettingsRoute =
  LibrariesLibraryIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => LibrariesLibraryIdRoute,
  } as any)
const LibrariesLibraryIdMoviesRoute =
  LibrariesLibraryIdMoviesRouteImport.update({
    id: '/movies',
    path: '/movies',
    getParentRoute: () => LibrariesLibraryIdRoute,
  } as any)
const LibrariesLibraryIdCollectionsRoute =
  LibrariesLibraryIdCollectionsRouteImport.update({
    id: '/collections',
    path: '/collections',
    getParentRoute: () => LibrariesLibraryIdRoute,
  } as any)
const LibrariesLibraryIdBrowserRoute =
  LibrariesLibraryIdBrowserRouteImport.update({
    id: '/browser',
    path: '/browser',
    getParentRoute: () => LibrariesLibraryIdRoute,
  } as any)
const LibrariesLibraryIdBooksRoute = LibrariesLibraryIdBooksRouteImport.update({
  id: '/books',
  path: '/books',
  getParentRoute: () => LibrariesLibraryIdRoute,
} as any)
const LibrariesLibraryIdAuthorsRoute =
  LibrariesLibraryIdAuthorsRouteImport.update({
    id: '/authors',
    path: '/authors',
    getParentRoute: () => LibrariesLibraryIdRoute,
  } as any)
const LibrariesLibraryIdArtistsRoute =
  LibrariesLibraryIdArtistsRouteImport.update({
    id: '/artists',
    path: '/artists',
    getParentRoute: () => LibrariesLibraryIdRoute,
  } as any)
const LibrariesLibraryIdAlbumsRoute =
  LibrariesLibraryIdAlbumsRouteImport.update({
    id: '/albums',
    path: '/albums',
    getParentRoute: () => LibrariesLibraryIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/hunt': typeof HuntRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRouteWithChildren
  '/albums/$albumId': typeof AlbumsAlbumIdRoute
  '/auth/login': typeof AuthLoginRoute
  '/libraries/$libraryId': typeof LibrariesLibraryIdRouteWithChildren
  '/movies/$movieId': typeof MoviesMovieIdRoute
  '/settings/casting': typeof SettingsCastingRoute
  '/settings/indexers': typeof SettingsIndexersRoute
  '/settings/logs': typeof SettingsLogsRoute
  '/settings/metadata': typeof SettingsMetadataRoute
  '/settings/organization': typeof SettingsOrganizationRoute
  '/settings/parser': typeof SettingsParserRoute
  '/settings/rss': typeof SettingsRssRoute
  '/settings/source-priorities': typeof SettingsSourcePrioritiesRoute
  '/settings/torrent': typeof SettingsTorrentRoute
  '/settings/usenet': typeof SettingsUsenetRoute
  '/shows/$showId': typeof ShowsShowIdRoute
  '/downloads/': typeof DownloadsIndexRoute
  '/libraries/': typeof LibrariesIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/libraries/$libraryId/albums': typeof LibrariesLibraryIdAlbumsRoute
  '/libraries/$libraryId/artists': typeof LibrariesLibraryIdArtistsRoute
  '/libraries/$libraryId/authors': typeof LibrariesLibraryIdAuthorsRoute
  '/libraries/$libraryId/books': typeof LibrariesLibraryIdBooksRoute
  '/libraries/$libraryId/browser': typeof LibrariesLibraryIdBrowserRoute
  '/libraries/$libraryId/collections': typeof LibrariesLibraryIdCollectionsRoute
  '/libraries/$libraryId/movies': typeof LibrariesLibraryIdMoviesRoute
  '/libraries/$libraryId/settings': typeof LibrariesLibraryIdSettingsRoute
  '/libraries/$libraryId/shows': typeof LibrariesLibraryIdShowsRoute
  '/libraries/$libraryId/tracks': typeof LibrariesLibraryIdTracksRoute
  '/libraries/$libraryId/unmatched': typeof LibrariesLibraryIdUnmatchedRoute
  '/libraries/$libraryId/': typeof LibrariesLibraryIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/hunt': typeof HuntRoute
  '/search': typeof SearchRoute
  '/albums/$albumId': typeof AlbumsAlbumIdRoute
  '/auth/login': typeof AuthLoginRoute
  '/movies/$movieId': typeof MoviesMovieIdRoute
  '/settings/casting': typeof SettingsCastingRoute
  '/settings/indexers': typeof SettingsIndexersRoute
  '/settings/logs': typeof SettingsLogsRoute
  '/settings/metadata': typeof SettingsMetadataRoute
  '/settings/organization': typeof SettingsOrganizationRoute
  '/settings/parser': typeof SettingsParserRoute
  '/settings/rss': typeof SettingsRssRoute
  '/settings/source-priorities': typeof SettingsSourcePrioritiesRoute
  '/settings/torrent': typeof SettingsTorrentRoute
  '/settings/usenet': typeof SettingsUsenetRoute
  '/shows/$showId': typeof ShowsShowIdRoute
  '/downloads': typeof DownloadsIndexRoute
  '/libraries': typeof LibrariesIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/libraries/$libraryId/albums': typeof LibrariesLibraryIdAlbumsRoute
  '/libraries/$libraryId/artists': typeof LibrariesLibraryIdArtistsRoute
  '/libraries/$libraryId/authors': typeof LibrariesLibraryIdAuthorsRoute
  '/libraries/$libraryId/books': typeof LibrariesLibraryIdBooksRoute
  '/libraries/$libraryId/browser': typeof LibrariesLibraryIdBrowserRoute
  '/libraries/$libraryId/collections': typeof LibrariesLibraryIdCollectionsRoute
  '/libraries/$libraryId/movies': typeof LibrariesLibraryIdMoviesRoute
  '/libraries/$libraryId/settings': typeof LibrariesLibraryIdSettingsRoute
  '/libraries/$libraryId/shows': typeof LibrariesLibraryIdShowsRoute
  '/libraries/$libraryId/tracks': typeof LibrariesLibraryIdTracksRoute
  '/libraries/$libraryId/unmatched': typeof LibrariesLibraryIdUnmatchedRoute
  '/libraries/$libraryId': typeof LibrariesLibraryIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/hunt': typeof HuntRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRouteWithChildren
  '/albums/$albumId': typeof AlbumsAlbumIdRoute
  '/auth/login': typeof AuthLoginRoute
  '/libraries/$libraryId': typeof LibrariesLibraryIdRouteWithChildren
  '/movies/$movieId': typeof MoviesMovieIdRoute
  '/settings/casting': typeof SettingsCastingRoute
  '/settings/indexers': typeof SettingsIndexersRoute
  '/settings/logs': typeof SettingsLogsRoute
  '/settings/metadata': typeof SettingsMetadataRoute
  '/settings/organization': typeof SettingsOrganizationRoute
  '/settings/parser': typeof SettingsParserRoute
  '/settings/rss': typeof SettingsRssRoute
  '/settings/source-priorities': typeof SettingsSourcePrioritiesRoute
  '/settings/torrent': typeof SettingsTorrentRoute
  '/settings/usenet': typeof SettingsUsenetRoute
  '/shows/$showId': typeof ShowsShowIdRoute
  '/downloads/': typeof DownloadsIndexRoute
  '/libraries/': typeof LibrariesIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/libraries/$libraryId/albums': typeof LibrariesLibraryIdAlbumsRoute
  '/libraries/$libraryId/artists': typeof LibrariesLibraryIdArtistsRoute
  '/libraries/$libraryId/authors': typeof LibrariesLibraryIdAuthorsRoute
  '/libraries/$libraryId/books': typeof LibrariesLibraryIdBooksRoute
  '/libraries/$libraryId/browser': typeof LibrariesLibraryIdBrowserRoute
  '/libraries/$libraryId/collections': typeof LibrariesLibraryIdCollectionsRoute
  '/libraries/$libraryId/movies': typeof LibrariesLibraryIdMoviesRoute
  '/libraries/$libraryId/settings': typeof LibrariesLibraryIdSettingsRoute
  '/libraries/$libraryId/shows': typeof LibrariesLibraryIdShowsRoute
  '/libraries/$libraryId/tracks': typeof LibrariesLibraryIdTracksRoute
  '/libraries/$libraryId/unmatched': typeof LibrariesLibraryIdUnmatchedRoute
  '/libraries/$libraryId/': typeof LibrariesLibraryIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/hunt'
    | '/search'
    | '/settings'
    | '/albums/$albumId'
    | '/auth/login'
    | '/libraries/$libraryId'
    | '/movies/$movieId'
    | '/settings/casting'
    | '/settings/indexers'
    | '/settings/logs'
    | '/settings/metadata'
    | '/settings/organization'
    | '/settings/parser'
    | '/settings/rss'
    | '/settings/source-priorities'
    | '/settings/torrent'
    | '/settings/usenet'
    | '/shows/$showId'
    | '/downloads/'
    | '/libraries/'
    | '/settings/'
    | '/libraries/$libraryId/albums'
    | '/libraries/$libraryId/artists'
    | '/libraries/$libraryId/authors'
    | '/libraries/$libraryId/books'
    | '/libraries/$libraryId/browser'
    | '/libraries/$libraryId/collections'
    | '/libraries/$libraryId/movies'
    | '/libraries/$libraryId/settings'
    | '/libraries/$libraryId/shows'
    | '/libraries/$libraryId/tracks'
    | '/libraries/$libraryId/unmatched'
    | '/libraries/$libraryId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/hunt'
    | '/search'
    | '/albums/$albumId'
    | '/auth/login'
    | '/movies/$movieId'
    | '/settings/casting'
    | '/settings/indexers'
    | '/settings/logs'
    | '/settings/metadata'
    | '/settings/organization'
    | '/settings/parser'
    | '/settings/rss'
    | '/settings/source-priorities'
    | '/settings/torrent'
    | '/settings/usenet'
    | '/shows/$showId'
    | '/downloads'
    | '/libraries'
    | '/settings'
    | '/libraries/$libraryId/albums'
    | '/libraries/$libraryId/artists'
    | '/libraries/$libraryId/authors'
    | '/libraries/$libraryId/books'
    | '/libraries/$libraryId/browser'
    | '/libraries/$libraryId/collections'
    | '/libraries/$libraryId/movies'
    | '/libraries/$libraryId/settings'
    | '/libraries/$libraryId/shows'
    | '/libraries/$libraryId/tracks'
    | '/libraries/$libraryId/unmatched'
    | '/libraries/$libraryId'
  id:
    | '__root__'
    | '/'
    | '/hunt'
    | '/search'
    | '/settings'
    | '/albums/$albumId'
    | '/auth/login'
    | '/libraries/$libraryId'
    | '/movies/$movieId'
    | '/settings/casting'
    | '/settings/indexers'
    | '/settings/logs'
    | '/settings/metadata'
    | '/settings/organization'
    | '/settings/parser'
    | '/settings/rss'
    | '/settings/source-priorities'
    | '/settings/torrent'
    | '/settings/usenet'
    | '/shows/$showId'
    | '/downloads/'
    | '/libraries/'
    | '/settings/'
    | '/libraries/$libraryId/albums'
    | '/libraries/$libraryId/artists'
    | '/libraries/$libraryId/authors'
    | '/libraries/$libraryId/books'
    | '/libraries/$libraryId/browser'
    | '/libraries/$libraryId/collections'
    | '/libraries/$libraryId/movies'
    | '/libraries/$libraryId/settings'
    | '/libraries/$libraryId/shows'
    | '/libraries/$libraryId/tracks'
    | '/libraries/$libraryId/unmatched'
    | '/libraries/$libraryId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HuntRoute: typeof HuntRoute
  SearchRoute: typeof SearchRoute
  SettingsRoute: typeof SettingsRouteWithChildren
  AlbumsAlbumIdRoute: typeof AlbumsAlbumIdRoute
  AuthLoginRoute: typeof AuthLoginRoute
  LibrariesLibraryIdRoute: typeof LibrariesLibraryIdRouteWithChildren
  MoviesMovieIdRoute: typeof MoviesMovieIdRoute
  ShowsShowIdRoute: typeof ShowsShowIdRoute
  DownloadsIndexRoute: typeof DownloadsIndexRoute
  LibrariesIndexRoute: typeof LibrariesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hunt': {
      id: '/hunt'
      path: '/hunt'
      fullPath: '/hunt'
      preLoaderRoute: typeof HuntRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/libraries/': {
      id: '/libraries/'
      path: '/libraries'
      fullPath: '/libraries/'
      preLoaderRoute: typeof LibrariesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/downloads/': {
      id: '/downloads/'
      path: '/downloads'
      fullPath: '/downloads/'
      preLoaderRoute: typeof DownloadsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shows/$showId': {
      id: '/shows/$showId'
      path: '/shows/$showId'
      fullPath: '/shows/$showId'
      preLoaderRoute: typeof ShowsShowIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/usenet': {
      id: '/settings/usenet'
      path: '/usenet'
      fullPath: '/settings/usenet'
      preLoaderRoute: typeof SettingsUsenetRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/torrent': {
      id: '/settings/torrent'
      path: '/torrent'
      fullPath: '/settings/torrent'
      preLoaderRoute: typeof SettingsTorrentRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/source-priorities': {
      id: '/settings/source-priorities'
      path: '/source-priorities'
      fullPath: '/settings/source-priorities'
      preLoaderRoute: typeof SettingsSourcePrioritiesRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/rss': {
      id: '/settings/rss'
      path: '/rss'
      fullPath: '/settings/rss'
      preLoaderRoute: typeof SettingsRssRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/parser': {
      id: '/settings/parser'
      path: '/parser'
      fullPath: '/settings/parser'
      preLoaderRoute: typeof SettingsParserRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/organization': {
      id: '/settings/organization'
      path: '/organization'
      fullPath: '/settings/organization'
      preLoaderRoute: typeof SettingsOrganizationRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/metadata': {
      id: '/settings/metadata'
      path: '/metadata'
      fullPath: '/settings/metadata'
      preLoaderRoute: typeof SettingsMetadataRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/logs': {
      id: '/settings/logs'
      path: '/logs'
      fullPath: '/settings/logs'
      preLoaderRoute: typeof SettingsLogsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/indexers': {
      id: '/settings/indexers'
      path: '/indexers'
      fullPath: '/settings/indexers'
      preLoaderRoute: typeof SettingsIndexersRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/casting': {
      id: '/settings/casting'
      path: '/casting'
      fullPath: '/settings/casting'
      preLoaderRoute: typeof SettingsCastingRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/movies/$movieId': {
      id: '/movies/$movieId'
      path: '/movies/$movieId'
      fullPath: '/movies/$movieId'
      preLoaderRoute: typeof MoviesMovieIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/libraries/$libraryId': {
      id: '/libraries/$libraryId'
      path: '/libraries/$libraryId'
      fullPath: '/libraries/$libraryId'
      preLoaderRoute: typeof LibrariesLibraryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/albums/$albumId': {
      id: '/albums/$albumId'
      path: '/albums/$albumId'
      fullPath: '/albums/$albumId'
      preLoaderRoute: typeof AlbumsAlbumIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/libraries/$libraryId/': {
      id: '/libraries/$libraryId/'
      path: '/'
      fullPath: '/libraries/$libraryId/'
      preLoaderRoute: typeof LibrariesLibraryIdIndexRouteImport
      parentRoute: typeof LibrariesLibraryIdRoute
    }
    '/libraries/$libraryId/unmatched': {
      id: '/libraries/$libraryId/unmatched'
      path: '/unmatched'
      fullPath: '/libraries/$libraryId/unmatched'
      preLoaderRoute: typeof LibrariesLibraryIdUnmatchedRouteImport
      parentRoute: typeof LibrariesLibraryIdRoute
    }
    '/libraries/$libraryId/tracks': {
      id: '/libraries/$libraryId/tracks'
      path: '/tracks'
      fullPath: '/libraries/$libraryId/tracks'
      preLoaderRoute: typeof LibrariesLibraryIdTracksRouteImport
      parentRoute: typeof LibrariesLibraryIdRoute
    }
    '/libraries/$libraryId/shows': {
      id: '/libraries/$libraryId/shows'
      path: '/shows'
      fullPath: '/libraries/$libraryId/shows'
      preLoaderRoute: typeof LibrariesLibraryIdShowsRouteImport
      parentRoute: typeof LibrariesLibraryIdRoute
    }
    '/libraries/$libraryId/settings': {
      id: '/libraries/$libraryId/settings'
      path: '/settings'
      fullPath: '/libraries/$libraryId/settings'
      preLoaderRoute: typeof LibrariesLibraryIdSettingsRouteImport
      parentRoute: typeof LibrariesLibraryIdRoute
    }
    '/libraries/$libraryId/movies': {
      id: '/libraries/$libraryId/movies'
      path: '/movies'
      fullPath: '/libraries/$libraryId/movies'
      preLoaderRoute: typeof LibrariesLibraryIdMoviesRouteImport
      parentRoute: typeof LibrariesLibraryIdRoute
    }
    '/libraries/$libraryId/collections': {
      id: '/libraries/$libraryId/collections'
      path: '/collections'
      fullPath: '/libraries/$libraryId/collections'
      preLoaderRoute: typeof LibrariesLibraryIdCollectionsRouteImport
      parentRoute: typeof LibrariesLibraryIdRoute
    }
    '/libraries/$libraryId/browser': {
      id: '/libraries/$libraryId/browser'
      path: '/browser'
      fullPath: '/libraries/$libraryId/browser'
      preLoaderRoute: typeof LibrariesLibraryIdBrowserRouteImport
      parentRoute: typeof LibrariesLibraryIdRoute
    }
    '/libraries/$libraryId/books': {
      id: '/libraries/$libraryId/books'
      path: '/books'
      fullPath: '/libraries/$libraryId/books'
      preLoaderRoute: typeof LibrariesLibraryIdBooksRouteImport
      parentRoute: typeof LibrariesLibraryIdRoute
    }
    '/libraries/$libraryId/authors': {
      id: '/libraries/$libraryId/authors'
      path: '/authors'
      fullPath: '/libraries/$libraryId/authors'
      preLoaderRoute: typeof LibrariesLibraryIdAuthorsRouteImport
      parentRoute: typeof LibrariesLibraryIdRoute
    }
    '/libraries/$libraryId/artists': {
      id: '/libraries/$libraryId/artists'
      path: '/artists'
      fullPath: '/libraries/$libraryId/artists'
      preLoaderRoute: typeof LibrariesLibraryIdArtistsRouteImport
      parentRoute: typeof LibrariesLibraryIdRoute
    }
    '/libraries/$libraryId/albums': {
      id: '/libraries/$libraryId/albums'
      path: '/albums'
      fullPath: '/libraries/$libraryId/albums'
      preLoaderRoute: typeof LibrariesLibraryIdAlbumsRouteImport
      parentRoute: typeof LibrariesLibraryIdRoute
    }
  }
}

interface SettingsRouteChildren {
  SettingsCastingRoute: typeof SettingsCastingRoute
  SettingsIndexersRoute: typeof SettingsIndexersRoute
  SettingsLogsRoute: typeof SettingsLogsRoute
  SettingsMetadataRoute: typeof SettingsMetadataRoute
  SettingsOrganizationRoute: typeof SettingsOrganizationRoute
  SettingsParserRoute: typeof SettingsParserRoute
  SettingsRssRoute: typeof SettingsRssRoute
  SettingsSourcePrioritiesRoute: typeof SettingsSourcePrioritiesRoute
  SettingsTorrentRoute: typeof SettingsTorrentRoute
  SettingsUsenetRoute: typeof SettingsUsenetRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsCastingRoute: SettingsCastingRoute,
  SettingsIndexersRoute: SettingsIndexersRoute,
  SettingsLogsRoute: SettingsLogsRoute,
  SettingsMetadataRoute: SettingsMetadataRoute,
  SettingsOrganizationRoute: SettingsOrganizationRoute,
  SettingsParserRoute: SettingsParserRoute,
  SettingsRssRoute: SettingsRssRoute,
  SettingsSourcePrioritiesRoute: SettingsSourcePrioritiesRoute,
  SettingsTorrentRoute: SettingsTorrentRoute,
  SettingsUsenetRoute: SettingsUsenetRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

interface LibrariesLibraryIdRouteChildren {
  LibrariesLibraryIdAlbumsRoute: typeof LibrariesLibraryIdAlbumsRoute
  LibrariesLibraryIdArtistsRoute: typeof LibrariesLibraryIdArtistsRoute
  LibrariesLibraryIdAuthorsRoute: typeof LibrariesLibraryIdAuthorsRoute
  LibrariesLibraryIdBooksRoute: typeof LibrariesLibraryIdBooksRoute
  LibrariesLibraryIdBrowserRoute: typeof LibrariesLibraryIdBrowserRoute
  LibrariesLibraryIdCollectionsRoute: typeof LibrariesLibraryIdCollectionsRoute
  LibrariesLibraryIdMoviesRoute: typeof LibrariesLibraryIdMoviesRoute
  LibrariesLibraryIdSettingsRoute: typeof LibrariesLibraryIdSettingsRoute
  LibrariesLibraryIdShowsRoute: typeof LibrariesLibraryIdShowsRoute
  LibrariesLibraryIdTracksRoute: typeof LibrariesLibraryIdTracksRoute
  LibrariesLibraryIdUnmatchedRoute: typeof LibrariesLibraryIdUnmatchedRoute
  LibrariesLibraryIdIndexRoute: typeof LibrariesLibraryIdIndexRoute
}

const LibrariesLibraryIdRouteChildren: LibrariesLibraryIdRouteChildren = {
  LibrariesLibraryIdAlbumsRoute: LibrariesLibraryIdAlbumsRoute,
  LibrariesLibraryIdArtistsRoute: LibrariesLibraryIdArtistsRoute,
  LibrariesLibraryIdAuthorsRoute: LibrariesLibraryIdAuthorsRoute,
  LibrariesLibraryIdBooksRoute: LibrariesLibraryIdBooksRoute,
  LibrariesLibraryIdBrowserRoute: LibrariesLibraryIdBrowserRoute,
  LibrariesLibraryIdCollectionsRoute: LibrariesLibraryIdCollectionsRoute,
  LibrariesLibraryIdMoviesRoute: LibrariesLibraryIdMoviesRoute,
  LibrariesLibraryIdSettingsRoute: LibrariesLibraryIdSettingsRoute,
  LibrariesLibraryIdShowsRoute: LibrariesLibraryIdShowsRoute,
  LibrariesLibraryIdTracksRoute: LibrariesLibraryIdTracksRoute,
  LibrariesLibraryIdUnmatchedRoute: LibrariesLibraryIdUnmatchedRoute,
  LibrariesLibraryIdIndexRoute: LibrariesLibraryIdIndexRoute,
}

const LibrariesLibraryIdRouteWithChildren =
  LibrariesLibraryIdRoute._addFileChildren(LibrariesLibraryIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HuntRoute: HuntRoute,
  SearchRoute: SearchRoute,
  SettingsRoute: SettingsRouteWithChildren,
  AlbumsAlbumIdRoute: AlbumsAlbumIdRoute,
  AuthLoginRoute: AuthLoginRoute,
  LibrariesLibraryIdRoute: LibrariesLibraryIdRouteWithChildren,
  MoviesMovieIdRoute: MoviesMovieIdRoute,
  ShowsShowIdRoute: ShowsShowIdRoute,
  DownloadsIndexRoute: DownloadsIndexRoute,
  LibrariesIndexRoute: LibrariesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
