/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SubscriptionsIndexRouteImport } from './routes/subscriptions/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as LibrariesIndexRouteImport } from './routes/libraries/index'
import { Route as DownloadsIndexRouteImport } from './routes/downloads/index'
import { Route as ShowsShowIdRouteImport } from './routes/shows/$showId'
import { Route as SettingsTorrentRouteImport } from './routes/settings/torrent'
import { Route as SettingsRssRouteImport } from './routes/settings/rss'
import { Route as SettingsMetadataRouteImport } from './routes/settings/metadata'
import { Route as SettingsLogsRouteImport } from './routes/settings/logs'
import { Route as SettingsIndexersRouteImport } from './routes/settings/indexers'
import { Route as SettingsCastingRouteImport } from './routes/settings/casting'
import { Route as LibrariesLibraryIdRouteImport } from './routes/libraries/$libraryId'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as LibrariesLibraryIdIndexRouteImport } from './routes/libraries/$libraryId/index'
import { Route as LibrariesLibraryIdUnmatchedRouteImport } from './routes/libraries/$libraryId/unmatched'
import { Route as LibrariesLibraryIdShowsRouteImport } from './routes/libraries/$libraryId/shows'
import { Route as LibrariesLibraryIdSettingsRouteImport } from './routes/libraries/$libraryId/settings'
import { Route as LibrariesLibraryIdBrowserRouteImport } from './routes/libraries/$libraryId/browser'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscriptionsIndexRoute = SubscriptionsIndexRouteImport.update({
  id: '/subscriptions/',
  path: '/subscriptions/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRoute,
} as any)
const LibrariesIndexRoute = LibrariesIndexRouteImport.update({
  id: '/libraries/',
  path: '/libraries/',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadsIndexRoute = DownloadsIndexRouteImport.update({
  id: '/downloads/',
  path: '/downloads/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShowsShowIdRoute = ShowsShowIdRouteImport.update({
  id: '/shows/$showId',
  path: '/shows/$showId',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsTorrentRoute = SettingsTorrentRouteImport.update({
  id: '/torrent',
  path: '/torrent',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsRssRoute = SettingsRssRouteImport.update({
  id: '/rss',
  path: '/rss',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsMetadataRoute = SettingsMetadataRouteImport.update({
  id: '/metadata',
  path: '/metadata',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsLogsRoute = SettingsLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsIndexersRoute = SettingsIndexersRouteImport.update({
  id: '/indexers',
  path: '/indexers',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsCastingRoute = SettingsCastingRouteImport.update({
  id: '/casting',
  path: '/casting',
  getParentRoute: () => SettingsRoute,
} as any)
const LibrariesLibraryIdRoute = LibrariesLibraryIdRouteImport.update({
  id: '/libraries/$libraryId',
  path: '/libraries/$libraryId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LibrariesLibraryIdIndexRoute = LibrariesLibraryIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LibrariesLibraryIdRoute,
} as any)
const LibrariesLibraryIdUnmatchedRoute =
  LibrariesLibraryIdUnmatchedRouteImport.update({
    id: '/unmatched',
    path: '/unmatched',
    getParentRoute: () => LibrariesLibraryIdRoute,
  } as any)
const LibrariesLibraryIdShowsRoute = LibrariesLibraryIdShowsRouteImport.update({
  id: '/shows',
  path: '/shows',
  getParentRoute: () => LibrariesLibraryIdRoute,
} as any)
const LibrariesLibraryIdSettingsRoute =
  LibrariesLibraryIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => LibrariesLibraryIdRoute,
  } as any)
const LibrariesLibraryIdBrowserRoute =
  LibrariesLibraryIdBrowserRouteImport.update({
    id: '/browser',
    path: '/browser',
    getParentRoute: () => LibrariesLibraryIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/libraries/$libraryId': typeof LibrariesLibraryIdRouteWithChildren
  '/settings/casting': typeof SettingsCastingRoute
  '/settings/indexers': typeof SettingsIndexersRoute
  '/settings/logs': typeof SettingsLogsRoute
  '/settings/metadata': typeof SettingsMetadataRoute
  '/settings/rss': typeof SettingsRssRoute
  '/settings/torrent': typeof SettingsTorrentRoute
  '/shows/$showId': typeof ShowsShowIdRoute
  '/downloads': typeof DownloadsIndexRoute
  '/libraries': typeof LibrariesIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/subscriptions': typeof SubscriptionsIndexRoute
  '/libraries/$libraryId/browser': typeof LibrariesLibraryIdBrowserRoute
  '/libraries/$libraryId/settings': typeof LibrariesLibraryIdSettingsRoute
  '/libraries/$libraryId/shows': typeof LibrariesLibraryIdShowsRoute
  '/libraries/$libraryId/unmatched': typeof LibrariesLibraryIdUnmatchedRoute
  '/libraries/$libraryId/': typeof LibrariesLibraryIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/login': typeof AuthLoginRoute
  '/settings/casting': typeof SettingsCastingRoute
  '/settings/indexers': typeof SettingsIndexersRoute
  '/settings/logs': typeof SettingsLogsRoute
  '/settings/metadata': typeof SettingsMetadataRoute
  '/settings/rss': typeof SettingsRssRoute
  '/settings/torrent': typeof SettingsTorrentRoute
  '/shows/$showId': typeof ShowsShowIdRoute
  '/downloads': typeof DownloadsIndexRoute
  '/libraries': typeof LibrariesIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/subscriptions': typeof SubscriptionsIndexRoute
  '/libraries/$libraryId/browser': typeof LibrariesLibraryIdBrowserRoute
  '/libraries/$libraryId/settings': typeof LibrariesLibraryIdSettingsRoute
  '/libraries/$libraryId/shows': typeof LibrariesLibraryIdShowsRoute
  '/libraries/$libraryId/unmatched': typeof LibrariesLibraryIdUnmatchedRoute
  '/libraries/$libraryId': typeof LibrariesLibraryIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/settings': typeof SettingsRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/libraries/$libraryId': typeof LibrariesLibraryIdRouteWithChildren
  '/settings/casting': typeof SettingsCastingRoute
  '/settings/indexers': typeof SettingsIndexersRoute
  '/settings/logs': typeof SettingsLogsRoute
  '/settings/metadata': typeof SettingsMetadataRoute
  '/settings/rss': typeof SettingsRssRoute
  '/settings/torrent': typeof SettingsTorrentRoute
  '/shows/$showId': typeof ShowsShowIdRoute
  '/downloads/': typeof DownloadsIndexRoute
  '/libraries/': typeof LibrariesIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/subscriptions/': typeof SubscriptionsIndexRoute
  '/libraries/$libraryId/browser': typeof LibrariesLibraryIdBrowserRoute
  '/libraries/$libraryId/settings': typeof LibrariesLibraryIdSettingsRoute
  '/libraries/$libraryId/shows': typeof LibrariesLibraryIdShowsRoute
  '/libraries/$libraryId/unmatched': typeof LibrariesLibraryIdUnmatchedRoute
  '/libraries/$libraryId/': typeof LibrariesLibraryIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/auth/login'
    | '/libraries/$libraryId'
    | '/settings/casting'
    | '/settings/indexers'
    | '/settings/logs'
    | '/settings/metadata'
    | '/settings/rss'
    | '/settings/torrent'
    | '/shows/$showId'
    | '/downloads'
    | '/libraries'
    | '/settings/'
    | '/subscriptions'
    | '/libraries/$libraryId/browser'
    | '/libraries/$libraryId/settings'
    | '/libraries/$libraryId/shows'
    | '/libraries/$libraryId/unmatched'
    | '/libraries/$libraryId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/login'
    | '/settings/casting'
    | '/settings/indexers'
    | '/settings/logs'
    | '/settings/metadata'
    | '/settings/rss'
    | '/settings/torrent'
    | '/shows/$showId'
    | '/downloads'
    | '/libraries'
    | '/settings'
    | '/subscriptions'
    | '/libraries/$libraryId/browser'
    | '/libraries/$libraryId/settings'
    | '/libraries/$libraryId/shows'
    | '/libraries/$libraryId/unmatched'
    | '/libraries/$libraryId'
  id:
    | '__root__'
    | '/'
    | '/settings'
    | '/auth/login'
    | '/libraries/$libraryId'
    | '/settings/casting'
    | '/settings/indexers'
    | '/settings/logs'
    | '/settings/metadata'
    | '/settings/rss'
    | '/settings/torrent'
    | '/shows/$showId'
    | '/downloads/'
    | '/libraries/'
    | '/settings/'
    | '/subscriptions/'
    | '/libraries/$libraryId/browser'
    | '/libraries/$libraryId/settings'
    | '/libraries/$libraryId/shows'
    | '/libraries/$libraryId/unmatched'
    | '/libraries/$libraryId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SettingsRoute: typeof SettingsRouteWithChildren
  AuthLoginRoute: typeof AuthLoginRoute
  LibrariesLibraryIdRoute: typeof LibrariesLibraryIdRouteWithChildren
  ShowsShowIdRoute: typeof ShowsShowIdRoute
  DownloadsIndexRoute: typeof DownloadsIndexRoute
  LibrariesIndexRoute: typeof LibrariesIndexRoute
  SubscriptionsIndexRoute: typeof SubscriptionsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscriptions/': {
      id: '/subscriptions/'
      path: '/subscriptions'
      fullPath: '/subscriptions'
      preLoaderRoute: typeof SubscriptionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/libraries/': {
      id: '/libraries/'
      path: '/libraries'
      fullPath: '/libraries'
      preLoaderRoute: typeof LibrariesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/downloads/': {
      id: '/downloads/'
      path: '/downloads'
      fullPath: '/downloads'
      preLoaderRoute: typeof DownloadsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shows/$showId': {
      id: '/shows/$showId'
      path: '/shows/$showId'
      fullPath: '/shows/$showId'
      preLoaderRoute: typeof ShowsShowIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/torrent': {
      id: '/settings/torrent'
      path: '/torrent'
      fullPath: '/settings/torrent'
      preLoaderRoute: typeof SettingsTorrentRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/rss': {
      id: '/settings/rss'
      path: '/rss'
      fullPath: '/settings/rss'
      preLoaderRoute: typeof SettingsRssRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/metadata': {
      id: '/settings/metadata'
      path: '/metadata'
      fullPath: '/settings/metadata'
      preLoaderRoute: typeof SettingsMetadataRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/logs': {
      id: '/settings/logs'
      path: '/logs'
      fullPath: '/settings/logs'
      preLoaderRoute: typeof SettingsLogsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/indexers': {
      id: '/settings/indexers'
      path: '/indexers'
      fullPath: '/settings/indexers'
      preLoaderRoute: typeof SettingsIndexersRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/casting': {
      id: '/settings/casting'
      path: '/casting'
      fullPath: '/settings/casting'
      preLoaderRoute: typeof SettingsCastingRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/libraries/$libraryId': {
      id: '/libraries/$libraryId'
      path: '/libraries/$libraryId'
      fullPath: '/libraries/$libraryId'
      preLoaderRoute: typeof LibrariesLibraryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/libraries/$libraryId/': {
      id: '/libraries/$libraryId/'
      path: '/'
      fullPath: '/libraries/$libraryId/'
      preLoaderRoute: typeof LibrariesLibraryIdIndexRouteImport
      parentRoute: typeof LibrariesLibraryIdRoute
    }
    '/libraries/$libraryId/unmatched': {
      id: '/libraries/$libraryId/unmatched'
      path: '/unmatched'
      fullPath: '/libraries/$libraryId/unmatched'
      preLoaderRoute: typeof LibrariesLibraryIdUnmatchedRouteImport
      parentRoute: typeof LibrariesLibraryIdRoute
    }
    '/libraries/$libraryId/shows': {
      id: '/libraries/$libraryId/shows'
      path: '/shows'
      fullPath: '/libraries/$libraryId/shows'
      preLoaderRoute: typeof LibrariesLibraryIdShowsRouteImport
      parentRoute: typeof LibrariesLibraryIdRoute
    }
    '/libraries/$libraryId/settings': {
      id: '/libraries/$libraryId/settings'
      path: '/settings'
      fullPath: '/libraries/$libraryId/settings'
      preLoaderRoute: typeof LibrariesLibraryIdSettingsRouteImport
      parentRoute: typeof LibrariesLibraryIdRoute
    }
    '/libraries/$libraryId/browser': {
      id: '/libraries/$libraryId/browser'
      path: '/browser'
      fullPath: '/libraries/$libraryId/browser'
      preLoaderRoute: typeof LibrariesLibraryIdBrowserRouteImport
      parentRoute: typeof LibrariesLibraryIdRoute
    }
  }
}

interface SettingsRouteChildren {
  SettingsCastingRoute: typeof SettingsCastingRoute
  SettingsIndexersRoute: typeof SettingsIndexersRoute
  SettingsLogsRoute: typeof SettingsLogsRoute
  SettingsMetadataRoute: typeof SettingsMetadataRoute
  SettingsRssRoute: typeof SettingsRssRoute
  SettingsTorrentRoute: typeof SettingsTorrentRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsCastingRoute: SettingsCastingRoute,
  SettingsIndexersRoute: SettingsIndexersRoute,
  SettingsLogsRoute: SettingsLogsRoute,
  SettingsMetadataRoute: SettingsMetadataRoute,
  SettingsRssRoute: SettingsRssRoute,
  SettingsTorrentRoute: SettingsTorrentRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

interface LibrariesLibraryIdRouteChildren {
  LibrariesLibraryIdBrowserRoute: typeof LibrariesLibraryIdBrowserRoute
  LibrariesLibraryIdSettingsRoute: typeof LibrariesLibraryIdSettingsRoute
  LibrariesLibraryIdShowsRoute: typeof LibrariesLibraryIdShowsRoute
  LibrariesLibraryIdUnmatchedRoute: typeof LibrariesLibraryIdUnmatchedRoute
  LibrariesLibraryIdIndexRoute: typeof LibrariesLibraryIdIndexRoute
}

const LibrariesLibraryIdRouteChildren: LibrariesLibraryIdRouteChildren = {
  LibrariesLibraryIdBrowserRoute: LibrariesLibraryIdBrowserRoute,
  LibrariesLibraryIdSettingsRoute: LibrariesLibraryIdSettingsRoute,
  LibrariesLibraryIdShowsRoute: LibrariesLibraryIdShowsRoute,
  LibrariesLibraryIdUnmatchedRoute: LibrariesLibraryIdUnmatchedRoute,
  LibrariesLibraryIdIndexRoute: LibrariesLibraryIdIndexRoute,
}

const LibrariesLibraryIdRouteWithChildren =
  LibrariesLibraryIdRoute._addFileChildren(LibrariesLibraryIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SettingsRoute: SettingsRouteWithChildren,
  AuthLoginRoute: AuthLoginRoute,
  LibrariesLibraryIdRoute: LibrariesLibraryIdRouteWithChildren,
  ShowsShowIdRoute: ShowsShowIdRoute,
  DownloadsIndexRoute: DownloadsIndexRoute,
  LibrariesIndexRoute: LibrariesIndexRoute,
  SubscriptionsIndexRoute: SubscriptionsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
