//! Show Entity
//!
//! This module contains the Show entity with macro-generated relations.
//! Relations use DataLoader batching to avoid N+1 queries.

use async_graphql::{Context, InputObject, Object, SimpleObject};
use std::sync::Arc;
use macros::{GraphQLEntity, GraphQLOperations, GraphQLRelations};
use serde::{Deserialize, Serialize};

use crate::graphql::auth::AuthExt;
use crate::graphql::entities::Library;

use super::common::AutoDownloadMode;
use super::episode::Episode;
use crate::services::metadata::providers::{AddTvShowOptions, MetadataProvider, MetadataService};

/// Show entity representing a TV show.
///
/// The Episodes relation is automatically generated by the GraphQLRelations macro
/// and uses DataLoader for N+1 prevention. Query with:
/// ```graphql
/// Show {
///   Episodes(Page: { Limit: 10 }) {
///     Edges { Node { ... } }
///     PageInfo { TotalCount }
///   }
/// }
/// ```
#[derive(
    GraphQLEntity,
    GraphQLRelations,
    GraphQLOperations,
    SimpleObject,
    Clone,
    Debug,
    Serialize,
    Deserialize,
)]
#[graphql(name = "Show", complex)]
#[serde(rename_all = "PascalCase")]
#[graphql_entity(
    table = "shows",
    plural = "Shows",
    default_sort = "name",
    notify = "libraries"
)]
pub struct Show {
    #[graphql(name = "Id")]
    #[primary_key]
    #[filterable(type = "string")]
    pub id: String,

    #[graphql(name = "LibraryId")]
    #[filterable(type = "string")]
    pub library_id: String,

    #[graphql(name = "UserId")]
    #[filterable(type = "string")]
    pub user_id: String,

    #[graphql(name = "Name")]
    #[filterable(type = "string")]
    #[sortable]
    pub name: String,

    #[graphql(name = "SortName")]
    #[sortable]
    pub sort_name: Option<String>,

    #[graphql(name = "Year")]
    #[filterable(type = "number")]
    #[sortable]
    pub year: Option<i32>,

    #[graphql(name = "TvmazeId")]
    #[filterable(type = "number")]
    pub tvmaze_id: Option<i32>,

    #[graphql(name = "TmdbId")]
    #[filterable(type = "number")]
    pub tmdb_id: Option<i32>,

    #[graphql(name = "TvdbId")]
    #[filterable(type = "number")]
    pub tvdb_id: Option<i32>,

    #[graphql(name = "ImdbId")]
    #[filterable(type = "string")]
    pub imdb_id: Option<String>,

    #[graphql(name = "Overview")]
    pub overview: Option<String>,

    #[graphql(name = "Network")]
    #[filterable(type = "string")]
    pub network: Option<String>,

    #[graphql(name = "Runtime")]
    #[filterable(type = "number")]
    pub runtime: Option<i32>,

    #[graphql(name = "Genres")]
    #[json_field]
    pub genres: Vec<String>,

    #[graphql(name = "PosterUrl")]
    pub poster_url: Option<String>,

    #[graphql(name = "BackdropUrl")]
    pub backdrop_url: Option<String>,

    #[graphql(name = "ContentRating")]
    #[filterable(type = "string")]
    pub content_rating: Option<String>,

    #[graphql(name = "AutoDownload")]
    #[filterable(type = "boolean")]
    pub auto_download: bool,

    #[graphql(name = "AutoDownloadMode")]
    pub auto_download_mode: AutoDownloadMode,

    #[graphql(name = "Path")]
    pub path: Option<String>,

    #[graphql(name = "CreatedAt")]
    #[filterable(type = "date")]
    #[sortable]
    pub created_at: String,

    #[graphql(name = "UpdatedAt")]
    #[filterable(type = "date")]
    #[sortable]
    pub updated_at: String,

    // ========================================================================
    // Relations - These generate ComplexObject resolvers via GraphQLRelations
    // ========================================================================
    //
    // Each relation:
    // - Exposes a GraphQL field with Where/OrderBy/Page args (for multiple relations)
    // - Uses DataLoader for batching when no args provided (N+1 free)
    // - Falls back to direct SQL query when args provided (full filter support)
    /// Parent library for this show
    #[graphql(skip)]
    #[serde(skip)]
    #[skip_db]
    #[relation(target = "Library", from = "library_id", to = "id")]
    pub library: Option<Library>,

    /// Episodes in this show
    #[graphql(skip)]
    #[serde(skip)]
    #[skip_db]
    #[relation(target = "Episode", to = "show_id", multiple)]
    pub episodes: Vec<Episode>,
}

#[derive(Default)]
pub struct ShowCustomOperations;

#[async_graphql::Object]
impl ShowCustomOperations {
    /// Search for TV shows on TVMaze
    #[graphql(name = "SearchTvShows")]
    async fn search_tv_shows(
        &self,
        ctx: &Context<'_>,
        #[graphql(name = "Query")] query: String,
    ) -> async_graphql::Result<Vec<TvShowSearchResultGql>> {
        let _user = ctx.auth_user()?;
        let metadata = ctx.data_unchecked::<Arc<MetadataService>>();

        let results = metadata
            .search_tv_shows(&query)
            .await
            .map_err(|e| async_graphql::Error::new(e.to_string()))?;

        Ok(results
            .into_iter()
            .map(|show| TvShowSearchResultGql {
                provider: match show.provider {
                    MetadataProvider::Tvmaze => "tvmaze".to_string(),
                    MetadataProvider::Tmdb => "tmdb".to_string(),
                    MetadataProvider::Musicbrainz => "musicbrainz".to_string(),
                    MetadataProvider::OpenLibrary => "openlibrary".to_string(),
                },
                provider_id: show.provider_id as i32,
                name: show.name,
                year: show.year,
                status: show.status,
                network: show.network,
                overview: show.overview,
                poster_url: show.poster_url,
                tvdb_id: show.tvdb_id,
                imdb_id: show.imdb_id,
                score: show.score,
            })
            .collect())
    }
}

// ============================================================================
// TV Show Metadata Mutations (TVMaze integration)
// ============================================================================

/// Input for searching TV shows
#[derive(Debug, InputObject)]
#[graphql(name = "SearchTvShowsInput")]
pub struct SearchTvShowsInput {
    #[graphql(name = "Query")]
    pub query: String,
}

/// Input for adding a TV show from TVMaze
#[derive(Debug, InputObject)]
#[graphql(name = "AddTvShowInput")]
pub struct AddTvShowInput {
    /// TVMaze show ID
    #[graphql(name = "TvmazeId")]
    pub tvmaze_id: i32,
    /// Auto-download mode for episodes
    #[graphql(name = "AutoDownloadMode")]
    pub auto_download_mode: Option<AutoDownloadMode>,
    /// Optional path override for the show
    #[graphql(name = "Path")]
    pub path: Option<String>,
}

/// TV show search result from TVMaze
#[derive(Debug, Clone, async_graphql::SimpleObject)]
#[graphql(name = "TvShowSearchResult")]
pub struct TvShowSearchResultGql {
    #[graphql(name = "Provider")]
    pub provider: String,
    #[graphql(name = "ProviderId")]
    pub provider_id: i32,
    #[graphql(name = "Name")]
    pub name: String,
    #[graphql(name = "Year")]
    pub year: Option<i32>,
    #[graphql(name = "Status")]
    pub status: Option<String>,
    #[graphql(name = "Network")]
    pub network: Option<String>,
    #[graphql(name = "Overview")]
    pub overview: Option<String>,
    #[graphql(name = "PosterUrl")]
    pub poster_url: Option<String>,
    #[graphql(name = "TvdbId")]
    pub tvdb_id: Option<i32>,
    #[graphql(name = "ImdbId")]
    pub imdb_id: Option<String>,
    #[graphql(name = "Score")]
    pub score: Option<f64>,
}

/// Result of TV show operations
#[derive(Debug, async_graphql::SimpleObject)]
#[graphql(name = "TvShowOperationResult")]
pub struct TvShowOperationResult {
    #[graphql(name = "Success")]
    pub success: bool,
    #[graphql(name = "Show")]
    pub show: Option<Show>,
    #[graphql(name = "Error")]
    pub error: Option<String>,
}

/// TV show metadata mutations (TVMaze integration)
#[derive(Default)]
pub struct ShowMetadataMutations;

#[Object]
impl ShowMetadataMutations {
    /// Add a TV show to a library by fetching metadata from TVMaze
    #[graphql(name = "AddTvShow")]
    async fn add_tv_show(
        &self,
        ctx: &Context<'_>,
        #[graphql(name = "LibraryId")] library_id: String,
        #[graphql(name = "Input")] input: AddTvShowInput,
    ) -> async_graphql::Result<TvShowOperationResult> {
        let user = ctx.auth_user()?;
        let metadata = ctx.data_unchecked::<Arc<MetadataService>>();

        let lib_id = uuid::Uuid::parse_str(&library_id)
            .map_err(|e| async_graphql::Error::new(format!("Invalid library ID: {}", e)))?;
        let user_id = uuid::Uuid::parse_str(&user.user_id)
            .map_err(|e| async_graphql::Error::new(format!("Invalid user ID: {}", e)))?;

        let monitor_type = input.auto_download_mode.unwrap_or(AutoDownloadMode::All);

        match metadata
            .add_tv_show_from_provider(AddTvShowOptions {
                provider: MetadataProvider::Tvmaze,
                provider_id: input.tvmaze_id as u32,
                library_id: lib_id,
                user_id,
                monitor_type,
                path: input.path,
            })
            .await
        {
            Ok(show) => Ok(TvShowOperationResult {
                success: true,
                show: Some(show),
                error: None,
            }),
            Err(e) => Ok(TvShowOperationResult {
                success: false,
                show: None,
                error: Some(e.to_string()),
            }),
        }
    }
}
