//! Show Entity
//!
//! This module contains the Show entity with macro-generated relations.
//! Relations use DataLoader batching to avoid N+1 queries.

use async_graphql::SimpleObject;
use librarian_macros::{GraphQLEntity, GraphQLOperations, GraphQLRelations};
use serde::{Deserialize, Serialize};

use super::episode::Episode;

/// Show entity representing a TV show.
///
/// The Episodes relation is automatically generated by the GraphQLRelations macro
/// and uses DataLoader for N+1 prevention.
#[derive(
    GraphQLEntity, GraphQLRelations, GraphQLOperations, SimpleObject, Clone, Debug, Serialize, Deserialize,
)]
#[graphql(name = "Show")]
#[serde(rename_all = "PascalCase")]
#[graphql_entity(
    table = "shows",
    plural = "Shows",
    default_sort = "name",
    notify = "libraries"
)]
pub struct Show {
    #[graphql(name = "Id")]
    #[primary_key]
    #[filterable(type = "string")]
    pub id: String,

    #[graphql(name = "LibraryId")]
    #[filterable(type = "string")]
    pub library_id: String,

    #[graphql(name = "UserId")]
    #[filterable(type = "string")]
    pub user_id: String,

    #[graphql(name = "Name")]
    #[filterable(type = "string")]
    #[sortable]
    pub name: String,

    #[graphql(name = "SortName")]
    #[sortable]
    pub sort_name: Option<String>,

    #[graphql(name = "Year")]
    #[filterable(type = "number")]
    #[sortable]
    pub year: Option<i32>,

    #[graphql(name = "Status")]
    #[filterable(type = "string")]
    pub status: Option<String>,

    #[graphql(name = "TvmazeId")]
    #[filterable(type = "number")]
    pub tvmaze_id: Option<i32>,

    #[graphql(name = "TmdbId")]
    #[filterable(type = "number")]
    pub tmdb_id: Option<i32>,

    #[graphql(name = "TvdbId")]
    #[filterable(type = "number")]
    pub tvdb_id: Option<i32>,

    #[graphql(name = "ImdbId")]
    #[filterable(type = "string")]
    pub imdb_id: Option<String>,

    #[graphql(name = "Overview")]
    pub overview: Option<String>,

    #[graphql(name = "Network")]
    #[filterable(type = "string")]
    pub network: Option<String>,

    #[graphql(name = "Runtime")]
    #[filterable(type = "number")]
    pub runtime: Option<i32>,

    #[graphql(name = "Genres")]
    #[json_field]
    pub genres: Vec<String>,

    #[graphql(name = "PosterUrl")]
    pub poster_url: Option<String>,

    #[graphql(name = "BackdropUrl")]
    pub backdrop_url: Option<String>,

    #[graphql(name = "ContentRating")]
    #[filterable(type = "string")]
    pub content_rating: Option<String>,

    #[graphql(name = "Monitored")]
    #[filterable(type = "boolean")]
    pub monitored: bool,

    #[graphql(name = "MonitorType")]
    #[filterable(type = "string")]
    pub monitor_type: String,

    #[graphql(name = "Path")]
    pub path: Option<String>,

    #[graphql(name = "EpisodeCount")]
    #[filterable(type = "number")]
    #[sortable]
    pub episode_count: Option<i32>,

    #[graphql(name = "EpisodeFileCount")]
    #[filterable(type = "number")]
    pub episode_file_count: Option<i32>,

    #[graphql(name = "SizeBytes")]
    #[filterable(type = "number")]
    #[sortable]
    pub size_bytes: Option<i64>,

    #[graphql(name = "CreatedAt")]
    #[filterable(type = "date")]
    #[sortable]
    pub created_at: String,

    #[graphql(name = "UpdatedAt")]
    #[filterable(type = "date")]
    #[sortable]
    pub updated_at: String,

    // ========================================================================
    // Relations
    // ========================================================================

    /// Episodes in this show
    #[graphql(skip)]
    #[serde(skip)]
    #[skip_db]
    #[relation(target = "Episode", to = "show_id", multiple)]
    pub episodes: Vec<Episode>,
}

#[derive(Default)]
pub struct ShowCustomOperations;

// Custom operations (SearchTvShows, AddTvShowFromProvider, etc.) can be added here
// as an #[Object] impl on ShowCustomOperations when needed.
