//! Show Entity
//!
//! This module contains the Show entity with macro-generated relations.
//! Relations use DataLoader batching to avoid N+1 queries.

use crate::graphql::entities::*;
use async_graphql::{Context, InputObject, Object};
use graphql_orm::{GraphQLEntity, GraphQLOperations, GraphQLRelations};
use serde::{Deserialize, Serialize};
use std::sync::Arc;

use crate::graphql::auth::AuthExt;
use crate::graphql::entities::Library;

use super::common::AutoDownloadMode;
use super::episode::Episode;
use crate::services::metadata::providers::{AddTvShowOptions, MetadataProvider, MetadataService};

/// Show entity representing a TV show.
///
/// The Episodes relation is automatically generated by the GraphQLRelations macro
/// and uses DataLoader for N+1 prevention. Query with:
/// ```graphql
/// Show {
///   Episodes(Page: { Limit: 10 }) {
///     Edges { Node { ... } }
///     PageInfo { TotalCount }
///   }
/// }
/// ```
#[derive(
    GraphQLEntity,
    GraphQLRelations,
    GraphQLOperations,
    async_graphql::SimpleObject,
    Clone,
    Debug,
    Serialize,
    Deserialize,
)]
#[graphql(complex)]
#[graphql(rename_fields = "camelCase")]
#[serde(rename_all = "PascalCase")]
#[graphql_entity(
    table = "shows",
    plural = "Shows",
    default_sort = "name",
    unique_composite = "library_id,tvmaze_id",
    unique_composite = "library_id,tmdb_id",
    unique_composite = "library_id,tvdb_id",
    unique_index = "library_id,tvmaze_id",
    unique_index = "library_id,tmdb_id",
    unique_index = "library_id,tvdb_id",
    upsert = "library_id,tvmaze_id"
)]
pub struct Show {
    #[graphql(name = "id")]
    #[primary_key]
    #[filterable(type = "string")]
    pub id: String,

    #[graphql(name = "libraryId")]
    #[filterable(type = "string")]
    pub library_id: String,

    #[graphql(name = "userId")]
    #[filterable(type = "string")]
    pub user_id: String,

    #[graphql(name = "name")]
    #[filterable(type = "string")]
    #[sortable]
    pub name: String,

    #[graphql(name = "sortName")]
    #[sortable]
    pub sort_name: Option<String>,

    #[graphql(name = "year")]
    #[filterable(type = "number")]
    #[sortable]
    pub year: Option<i32>,

    #[graphql(name = "tvmazeId")]
    #[filterable(type = "number")]
    pub tvmaze_id: Option<i32>,

    #[graphql(name = "tmdbId")]
    #[filterable(type = "number")]
    pub tmdb_id: Option<i32>,

    #[graphql(name = "tvdbId")]
    #[filterable(type = "number")]
    pub tvdb_id: Option<i32>,

    #[graphql(name = "imdbId")]
    #[filterable(type = "string")]
    pub imdb_id: Option<String>,

    #[graphql(name = "overview")]
    pub overview: Option<String>,

    #[graphql(name = "network")]
    #[filterable(type = "string")]
    pub network: Option<String>,

    #[graphql(name = "runtime")]
    #[filterable(type = "number")]
    pub runtime: Option<i32>,

    #[graphql(name = "genres")]
    #[json_field]
    pub genres: Vec<String>,

    #[graphql(name = "posterUrl")]
    pub poster_url: Option<String>,

    #[graphql(name = "backdropUrl")]
    pub backdrop_url: Option<String>,

    #[graphql(name = "contentRating")]
    #[filterable(type = "string")]
    pub content_rating: Option<String>,

    #[graphql(name = "autoDownload")]
    #[filterable(type = "boolean")]
    pub auto_download: bool,

    #[graphql(name = "autoDownloadMode")]
    pub auto_download_mode: AutoDownloadMode,

    /// Optional quality profile override; falls back to
    /// `Library.qualityProfileId` (then the seeded default) when unset.
    #[graphql(name = "qualityProfileId")]
    #[filterable(type = "string")]
    pub quality_profile_id: Option<String>,

    #[graphql(name = "path")]
    pub path: Option<String>,

    #[graphql(name = "createdAt")]
    #[filterable(type = "date")]
    #[sortable]
    pub created_at: String,

    #[graphql(name = "updatedAt")]
    #[filterable(type = "date")]
    #[sortable]
    pub updated_at: String,

    // ========================================================================
    // Relations - These generate ComplexObject resolvers via GraphQLRelations
    // ========================================================================
    //
    // Each relation:
    // - Exposes a GraphQL field with Where/OrderBy/Page args (for multiple relations)
    // - Uses DataLoader for batching when no args provided (N+1 free)
    // - Falls back to direct SQL query when args provided (full filter support)
    /// Parent library for this show
    #[graphql(skip)]
    #[serde(skip)]
    #[skip_db]
    #[relation(
        target = "Library",
        from = "library_id",
        to = "id",
        on_delete = "cascade"
    )]
    pub library: Option<Library>,

    /// Episodes in this show
    #[graphql(skip)]
    #[serde(skip)]
    #[skip_db]
    #[relation(target = "Episode", to = "show_id", multiple)]
    pub episodes: Vec<Episode>,
}

#[derive(Default)]
pub struct ShowCustomOperations;

#[async_graphql::Object]
impl ShowCustomOperations {
    /// Search for TV shows on TVMaze
    #[graphql(name = "searchTvShows")]
    async fn search_tv_shows(
        &self,
        ctx: &Context<'_>,
        #[graphql(name = "query")] query: String,
    ) -> async_graphql::Result<Vec<TvShowSearchResultGql>> {
        let _user = ctx.librarian_auth_user()?;
        let metadata = ctx.data_unchecked::<Arc<MetadataService>>();

        let results = metadata
            .search_tv_shows(&query)
            .await
            .map_err(|e| async_graphql::Error::new(e.to_string()))?;

        Ok(results
            .into_iter()
            .map(|show| TvShowSearchResultGql {
                provider: match show.provider {
                    MetadataProvider::Tvmaze => "tvmaze".to_string(),
                    MetadataProvider::Tmdb => "tmdb".to_string(),
                    MetadataProvider::Musicbrainz => "musicbrainz".to_string(),
                    MetadataProvider::OpenLibrary => "openlibrary".to_string(),
                },
                provider_id: show.provider_id as i32,
                name: show.name,
                year: show.year,
                status: show.status,
                network: show.network,
                overview: show.overview,
                poster_url: show.poster_url,
                tvdb_id: show.tvdb_id,
                imdb_id: show.imdb_id,
                score: show.score,
            })
            .collect())
    }
}

// ============================================================================
// TV Show Metadata Mutations (TVMaze integration)
// ============================================================================

/// Input for searching TV shows
#[derive(Debug, InputObject)]
#[graphql(name = "SearchTvShowsInput")]
pub struct SearchTvShowsInput {
    #[graphql(name = "query")]
    pub query: String,
}

/// Input for adding a TV show from TVMaze
#[derive(Debug, InputObject)]
#[graphql(name = "AddTvShowInput")]
pub struct AddTvShowInput {
    /// TVMaze show ID
    #[graphql(name = "tvmazeId")]
    pub tvmaze_id: i32,
    /// Auto-download mode for episodes
    #[graphql(name = "autoDownloadMode")]
    pub auto_download_mode: Option<AutoDownloadMode>,
    /// Optional path override for the show
    #[graphql(name = "path")]
    pub path: Option<String>,
}

/// TV show search result from TVMaze
#[derive(Debug, Clone, async_graphql::SimpleObject)]
#[graphql(name = "TvShowSearchResult")]
pub struct TvShowSearchResultGql {
    #[graphql(name = "provider")]
    pub provider: String,
    #[graphql(name = "providerId")]
    pub provider_id: i32,
    #[graphql(name = "name")]
    pub name: String,
    #[graphql(name = "year")]
    pub year: Option<i32>,
    #[graphql(name = "status")]
    pub status: Option<String>,
    #[graphql(name = "network")]
    pub network: Option<String>,
    #[graphql(name = "overview")]
    pub overview: Option<String>,
    #[graphql(name = "posterUrl")]
    pub poster_url: Option<String>,
    #[graphql(name = "tvdbId")]
    pub tvdb_id: Option<i32>,
    #[graphql(name = "imdbId")]
    pub imdb_id: Option<String>,
    #[graphql(name = "score")]
    pub score: Option<f64>,
}

/// Result of TV show operations
#[derive(Debug, async_graphql::SimpleObject)]
#[graphql(name = "TvShowOperationResult")]
pub struct TvShowOperationResult {
    #[graphql(name = "success")]
    pub success: bool,
    #[graphql(name = "show")]
    pub show: Option<Show>,
    #[graphql(name = "error")]
    pub error: Option<String>,
}

/// TV show metadata mutations (TVMaze integration)
#[derive(Default)]
pub struct ShowMetadataMutations;

#[Object]
impl ShowMetadataMutations {
    /// Add a TV show to a library by fetching metadata from TVMaze
    #[graphql(name = "addTvShow")]
    async fn add_tv_show(
        &self,
        ctx: &Context<'_>,
        #[graphql(name = "libraryId")] library_id: String,
        #[graphql(name = "input")] input: AddTvShowInput,
    ) -> async_graphql::Result<TvShowOperationResult> {
        let user = ctx.librarian_auth_user()?;
        let metadata = ctx.data_unchecked::<Arc<MetadataService>>();

        let lib_id = uuid::Uuid::parse_str(&library_id)
            .map_err(|e| async_graphql::Error::new(format!("Invalid library ID: {}", e)))?;
        let user_id = uuid::Uuid::parse_str(&user.user_id)
            .map_err(|e| async_graphql::Error::new(format!("Invalid user ID: {}", e)))?;

        let monitor_type = input.auto_download_mode.unwrap_or(AutoDownloadMode::All);

        match metadata
            .add_tv_show_from_provider(AddTvShowOptions {
                provider: MetadataProvider::Tvmaze,
                provider_id: input.tvmaze_id as u32,
                library_id: lib_id,
                user_id,
                monitor_type,
                path: input.path,
            })
            .await
        {
            Ok(show) => Ok(TvShowOperationResult {
                success: true,
                show: Some(show),
                error: None,
            }),
            Err(e) => Ok(TvShowOperationResult {
                success: false,
                show: None,
                error: Some(e.to_string()),
            }),
        }
    }

    /// Refresh a show's metadata and artwork from TVMaze.
    #[graphql(name = "refreshShow")]
    async fn refresh_show(
        &self,
        ctx: &Context<'_>,
        #[graphql(name = "id")] id: String,
    ) -> async_graphql::Result<TvShowOperationResult> {
        let user = ctx.librarian_auth_user()?;
        let metadata = ctx.data_unchecked::<Arc<MetadataService>>();

        let user_id = uuid::Uuid::parse_str(&user.user_id)
            .map_err(|e| async_graphql::Error::new(format!("Invalid user ID: {}", e)))?;

        match metadata.refresh_tv_show_from_provider(&id, user_id).await {
            Ok(show) => Ok(TvShowOperationResult {
                success: true,
                show: Some(show),
                error: None,
            }),
            Err(e) => Ok(TvShowOperationResult {
                success: false,
                show: None,
                error: Some(e.to_string()),
            }),
        }
    }
}
