//! GraphQL schema: the Rust `QueryRoot`, `MutationRoot`, and `SubscriptionRoot`
//! types are derived from the entity list via `schema_roots!` and exported as
//! the conventional GraphQL `Query`, `Mutation`, and `Subscription` objects.
//! Add a new entity in the entities module and in the list below;
//! Queries/Mutations/CustomOperations are generated by the macro.

use std::sync::Arc;

use async_graphql::Schema;
use graphql_orm::schema_roots;

use crate::db::Database;
use crate::services::graphql::entities::*;
use crate::services::graphql::mutations::{
    ArtworkMutations, AuthMutations, AutoDownloadMutations, BackupMutations, FilesystemMutations,
    LibraryScanMutations, NotificationFeedMutations, QualityMutations,
};
use crate::services::graphql::queries::{
    BackupQueries, ContentStatusQueries, FilesystemQueries, QualityQueries,
};
use crate::services::graphql::subscriptions::filesystem::FilesystemChangeBroker;
use crate::services::graphql::subscriptions::{FilesystemSubscriptions, TorrentSubscriptions};
use crate::services::manager::ServicesManager;
use crate::services::metadata::providers::{MetadataServiceConfig, create_metadata_service};

schema_roots! {
    query_custom_ops: [User, Torrent, Movie, Show, Album, Audiobook, ScheduleCache],
    entities: [
        Library,
        LibraryScanRun,
        LibraryScanIssue,
        Movie,
        Person,
        MovieCastCredit,
        Collection,
        Show,
        Episode,
        MediaFile,
        Artist,
        Album,
        Track,
        Audiobook,
        Chapter,
        Torrent,
        TorrentFile,
        RssFeed,
        RssFeedItem,
        PendingFileMatch,
        Source,
        User,
        InviteToken,
        RefreshToken,
        AppSetting,
        AppLog,
        VideoStream,
        AudioStream,
        Subtitle,
        MediaChapter,
        PlaybackSession,
        PlaybackProgress,
        CastDevice,
        CastSession,
        CastSetting,
        UsenetServer,
        UsenetDownload,
        ScheduleCache,
        ScheduleSyncState,
        NamingPattern,
        MetadataCache,
        SourcePriorityRule,
        Notification,
        TorznabCategory,
        QualityProfile,
        ReleaseBlocklist,
    ],
    extra_query_types: [FilesystemQueries, SourceCustomQueries, BackupQueries, QualityQueries, ContentStatusQueries],
    extra_mutation_types: [ArtworkMutations, AuthMutations, FilesystemMutations, LibraryScanMutations, TorrentClientMutations, MovieMetadataMutations, ShowMetadataMutations, AlbumMetadataMutations, AudiobookMetadataMutations, SourceCustomMutations, CastMutations, BackupMutations, AutoDownloadMutations, QualityMutations, NotificationFeedMutations],
    extra_subscription_types: [FilesystemSubscriptions, TorrentSubscriptions],
}

/// The GraphQL schema type
pub type LibrarianSchema = Schema<QueryRoot, MutationRoot, SubscriptionRoot>;

/// Build the GraphQL schema with all resolvers.
/// Pass the [ServicesManager] so resolvers can obtain the torrent service etc.
pub fn build_schema<E>(
    db: Database,
    auth_service: E,
    services: Arc<ServicesManager>,
) -> LibrarianSchema
where
    E: Send + Sync + Clone + 'static,
{
    // Create MetadataService - it will load API keys from database on demand
    let metadata_service = create_metadata_service(
        db.clone(),
        services.clone(),
        MetadataServiceConfig::default(),
    );

    // `schema_builder(db)` (graphql-orm) already applies production-safe defaults
    // (depth 16 / complexity 20_000). We set our own explicit, slightly more generous
    // depth cap and a tighter complexity cap sized for this schema's actual query shapes
    // (checked against the largest documents in frontend/src/lib/graphql/documents, which
    // top out around depth 7-8) — generous enough that legitimate queries never hit it,
    // but finite so a malicious/misbehaving client can't force unbounded work server-side.
    let mut builder = schema_builder(db)
        .data(auth_service)
        .data(services)
        .data(metadata_service)
        .data(FilesystemChangeBroker::new(64))
        .limit_depth(20)
        .limit_complexity(10_000);

    if !crate::config::dev_mode() {
        builder = builder.disable_introspection();
    }

    builder.finish()
}

#[cfg(test)]
mod tests {
    use std::sync::Arc;

    use graphql_orm::DbPool;
    use graphql_orm::graphql::orm::Entity;
    use serde::Deserialize;

    use super::*;
    use crate::services::{
        AuthConfig, BackupServiceConfig, DatabaseServiceConfig, GraphqlServiceConfig,
        ObjectStorageServiceConfig,
    };
    use std::time::Duration;

    #[derive(Debug, Deserialize, PartialEq, Eq, PartialOrd, Ord)]
    struct AuthorizationMatrixEntry {
        entity: String,
        read: String,
        write: String,
        scope: String,
    }

    fn effective_policy<T: Entity>() -> AuthorizationMatrixEntry {
        let metadata = T::metadata();
        AuthorizationMatrixEntry {
            entity: metadata.entity_name.to_string(),
            read: metadata.read_policy.unwrap_or("member.read").to_string(),
            write: metadata.write_policy.unwrap_or("member.write").to_string(),
            // Scope is asserted separately by OwnershipRowPolicy tests and is
            // carried in the fixture as the reviewable product classification.
            scope: String::new(),
        }
    }

    #[test]
    fn generated_entity_policies_match_the_authorization_matrix() {
        let mut expected: Vec<AuthorizationMatrixEntry> = serde_json::from_str(include_str!(
            "../../../tests/fixtures/authorization-matrix.json"
        ))
        .expect("authorization matrix fixture should parse");
        assert!(
            expected.iter().all(
                |entry| ["owner", "derived", "shared", "admin"].contains(&entry.scope.as_str())
            ),
            "every entity must have a recognized scope classification"
        );
        for entry in &mut expected {
            entry.scope.clear();
        }

        let mut actual = Vec::new();
        macro_rules! record {
            ($($entity:ty),+ $(,)?) => {
                $(actual.push(effective_policy::<$entity>());)+
            };
        }
        record!(
            Library,
            LibraryScanRun,
            LibraryScanIssue,
            Movie,
            Person,
            MovieCastCredit,
            Collection,
            Show,
            Episode,
            MediaFile,
            Artist,
            Album,
            Track,
            Audiobook,
            Chapter,
            Torrent,
            TorrentFile,
            RssFeed,
            RssFeedItem,
            PendingFileMatch,
            Source,
            User,
            InviteToken,
            RefreshToken,
            AppSetting,
            AppLog,
            VideoStream,
            AudioStream,
            Subtitle,
            MediaChapter,
            PlaybackSession,
            PlaybackProgress,
            CastDevice,
            CastSession,
            CastSetting,
            UsenetServer,
            UsenetDownload,
            ScheduleCache,
            ScheduleSyncState,
            NamingPattern,
            MetadataCache,
            SourcePriorityRule,
            Notification,
            TorznabCategory,
            QualityProfile,
            ReleaseBlocklist,
        );
        expected.sort();
        actual.sort();
        assert_eq!(actual, expected);
    }

    #[tokio::test]
    async fn schema_builds_without_recursing() {
        let pool = DbPool::connect("sqlite::memory:")
            .await
            .expect("in-memory database should connect");
        let db = Database::new(pool);
        let services = Arc::new(ServicesManager::new());

        let schema = build_schema(db, (), services);
        let sdl = schema.sdl();
        if let Ok(path) = std::env::var("EXPORT_GRAPHQL_SCHEMA") {
            std::fs::write(path, &sdl).expect("schema SDL should write");
        }

        assert!(sdl.contains("type Query {"));
        for operation in [
            "markAllNotificationsRead:",
            "updateNotification(",
            "deleteNotification(",
            "createNotification(",
        ] {
            assert!(
                sdl.contains(operation),
                "Notification feed operations must coexist with generated CRUD: {operation}"
            );
        }
        assert!(sdl.contains("BackupCapabilities"));
        assert!(sdl.contains("type CastDevice {"));
        assert!(sdl.contains("enabled: Boolean"));
        assert!(sdl.contains("playbackSupported: Boolean"));
        assert!(sdl.contains("discoveryOrigin: String"));
        assert!(sdl.contains("login(input: LoginInput!): AuthPayload!"));
    }

    #[tokio::test]
    async fn core_services_start_with_storage_and_backup_registered() {
        let temp_dir = tempfile::tempdir().expect("temp dir should create");
        let database_url = format!(
            "sqlite://{}",
            temp_dir.path().join("librarian.db").display()
        );

        let services = ServicesManager::builder()
            .add_service(DatabaseServiceConfig {
                database_url,
                connect_timeout: Duration::from_secs(5),
            })
            .add_service(ObjectStorageServiceConfig {
                backend: "local".to_string(),
                local_path: temp_dir.path().join("storage"),
            })
            .add_service(AuthConfig::for_tests())
            .add_service(GraphqlServiceConfig { server_port: 0 })
            .add_service(BackupServiceConfig {
                repository_path: temp_dir.path().join("backups"),
            })
            .start()
            .await
            .expect("core services should start");

        assert!(services.get_storage().await.is_some());
        assert!(services.get_backup().await.is_some());
        assert!(services.get_graphql().await.is_some());

        services
            .stop_all()
            .await
            .expect("core services should stop");
    }

    #[test]
    fn graphql_enforces_two_member_isolation_and_admin_override() {
        std::thread::Builder::new()
            .name("graphql-authorization-behavior".to_string())
            .stack_size(8 * 1024 * 1024)
            .spawn(|| {
                let runtime = tokio::runtime::Builder::new_current_thread()
                    .enable_all()
                    .build()
                    .expect("authorization runtime should build");
                runtime.block_on(graphql_authorization_behavior_case());
            })
            .expect("authorization test thread should spawn")
            .join()
            .expect("authorization test thread should not panic");
    }

    async fn graphql_authorization_behavior_case() {
        use async_graphql::Request;

        use crate::graphql::entities::{
            CreateLibraryInput, CreateUserInput, Library, UpdateLibraryInput, User,
        };
        use crate::services::graphql::AuthUser;

        let temp_dir = tempfile::tempdir().expect("temp dir should create");
        let database_url = format!(
            "sqlite://{}",
            temp_dir.path().join("authorization.db").display()
        );
        let services = ServicesManager::builder()
            .add_service(DatabaseServiceConfig {
                database_url,
                connect_timeout: Duration::from_secs(5),
            })
            .add_service(AuthConfig::for_tests())
            .add_service(GraphqlServiceConfig { server_port: 0 })
            .start()
            .await
            .expect("authorization services should start");
        let database = services
            .get_database()
            .await
            .expect("database service should exist");
        let graphql = services
            .get_graphql()
            .await
            .expect("graphql service should exist");
        let schema = graphql.schema().await.expect("schema should exist");

        async fn create_user(
            database: &crate::services::DatabaseService,
            id: &str,
            role: &str,
        ) -> User {
            User::insert(
                database.pool(),
                CreateUserInput {
                    username: id.to_string(),
                    email: Some(format!("{id}@example.test")),
                    password_hash: "test-only".to_string(),
                    role: role.to_string(),
                    display_name: None,
                    avatar_url: None,
                    is_active: true,
                    last_login_at: None,
                },
            )
            .await
            .expect("user fixture should insert")
        }

        let member_a = create_user(&database, "member-a", "Member").await;
        let member_b = create_user(&database, "member-b", "Member").await;
        let admin = create_user(&database, "admin-user", "Admin").await;

        async fn create_library(
            database: &crate::services::DatabaseService,
            user_id: String,
            name: &str,
            path: String,
        ) -> Library {
            Library::insert(
                database.pool(),
                CreateLibraryInput {
                    user_id,
                    name: name.to_string(),
                    path,
                    library_type: "movies".to_string(),
                    icon: None,
                    color: None,
                    auto_scan: false,
                    auto_organize: false,
                    naming_pattern: String::new(),
                    scan_interval_minutes: 60,
                    watch_for_changes: false,
                    scanning: false,
                    last_scanned_at: None,
                    quality_profile_id: None,
                },
            )
            .await
            .expect("library fixture should insert")
        }

        let library_a = create_library(
            &database,
            member_a.id.clone(),
            "Member A Library",
            temp_dir.path().join("a").to_string_lossy().to_string(),
        )
        .await;
        let library_b = create_library(
            &database,
            member_b.id.clone(),
            "Member B Library",
            temp_dir.path().join("b").to_string_lossy().to_string(),
        )
        .await;
        let member_a_auth = AuthUser {
            user_id: member_a.id.clone(),
            email: member_a.email.clone(),
            role: Some("Member".to_string()),
        };
        let admin_auth = AuthUser {
            user_id: admin.id,
            email: admin.email,
            role: Some("Admin".to_string()),
        };

        fn authenticated_request(document: impl Into<String>, auth_user: &AuthUser) -> Request {
            let subject = graphql_orm::graphql::auth::AuthSubject::from_parts(
                auth_user.user_id.clone(),
                auth_user.role.iter().cloned().collect(),
                Vec::new(),
                None,
            );
            Request::new(document).data(auth_user.clone()).data(subject)
        }

        let member_list = schema
            .execute(authenticated_request(
                "query { libraries(page: { limit: 100 }) { edges { node { id userId } } } }",
                &member_a_auth,
            ))
            .await;
        assert!(member_list.errors.is_empty(), "{:?}", member_list.errors);
        let member_json =
            serde_json::to_value(member_list.data).expect("member response should serialize");
        let member_edges = member_json["libraries"]["edges"]
            .as_array()
            .expect("member edges should be an array");
        assert_eq!(member_edges.len(), 1);
        assert_eq!(member_edges[0]["node"]["id"], library_a.id);

        let member_get_other = schema
            .execute(authenticated_request(
                format!(
                    "query {{ library(id: \"{}\") {{ id userId }} }}",
                    library_b.id
                ),
                &member_a_auth,
            ))
            .await;
        let get_json =
            serde_json::to_value(member_get_other.data).expect("get response should serialize");
        assert!(get_json["library"].is_null());

        let member_update_other = schema
            .execute(authenticated_request(
                format!(
                    "mutation {{ updateLibrary(id: \"{}\", input: {{ name: \"stolen\" }}) {{ success error }} }}",
                    library_b.id
                ),
                &member_a_auth,
            ))
            .await;
        assert!(
            !member_update_other.errors.is_empty()
                || serde_json::to_value(member_update_other.data)
                    .ok()
                    .and_then(|value| value["updateLibrary"]["success"].as_bool())
                    != Some(true)
        );
        assert_eq!(
            Library::get(database.pool().pool(), &library_b.id)
                .await
                .expect("other library should read")
                .expect("other library should exist")
                .name,
            "Member B Library"
        );

        let member_transfer = schema
            .execute(authenticated_request(
                format!(
                    "mutation {{ updateLibrary(id: \"{}\", input: {{ userId: \"{}\" }}) {{ success error }} }}",
                    library_a.id, member_b.id
                ),
                &member_a_auth,
            ))
            .await;
        assert!(
            !member_transfer.errors.is_empty()
                || serde_json::to_value(member_transfer.data)
                    .ok()
                    .and_then(|value| value["updateLibrary"]["success"].as_bool())
                    != Some(true)
        );
        assert_eq!(
            Library::get(database.pool().pool(), &library_a.id)
                .await
                .expect("own library should read")
                .expect("own library should exist")
                .user_id,
            member_a.id
        );

        let admin_list = schema
            .execute(authenticated_request(
                "query { libraries(page: { limit: 100 }) { edges { node { id userId } } } }",
                &admin_auth,
            ))
            .await;
        assert!(admin_list.errors.is_empty(), "{:?}", admin_list.errors);
        let admin_json =
            serde_json::to_value(admin_list.data).expect("admin response should serialize");
        assert_eq!(
            admin_json["libraries"]["edges"]
                .as_array()
                .expect("admin edges should be an array")
                .len(),
            2
        );

        let admin_update = schema
            .execute(authenticated_request(
                format!(
                    "mutation {{ updateLibrary(id: \"{}\", input: {{ name: \"Admin Updated\" }}) {{ success error }} }}",
                    library_b.id
                ),
                &admin_auth,
            ))
            .await;
        assert!(admin_update.errors.is_empty(), "{:?}", admin_update.errors);
        assert_eq!(
            Library::get(database.pool().pool(), &library_b.id)
                .await
                .expect("admin-updated library should read")
                .expect("admin-updated library should exist")
                .name,
            "Admin Updated"
        );

        // Repository writes remain available to internal jobs, but the public
        // member GraphQL surface above cannot cross the same row boundary.
        Library::update_by_id(
            database.pool(),
            &library_a.id,
            UpdateLibraryInput {
                scanning: Some(true),
                ..Default::default()
            },
        )
        .await
        .expect("internal repository update should remain available");

        services
            .stop_all()
            .await
            .expect("authorization services should stop");
    }
}
