//! GraphQL schema: QueryRoot and MutationRoot are derived from the entity list
//! via `schema_roots!`. Add a new entity in the entities module and in the
//! list below; Queries/Mutations/CustomOperations are generated by the macro.

use crate::db::Database;
use crate::services::graphql::auth_mutations::AuthMutations;
use crate::services::graphql::entities::*;
use async_graphql::Schema;
use librarian_macros::schema_roots;

schema_roots! {
    query_custom_ops: [User],
    entities: [
        Library,
        Movie,
        Show,
        Episode,
        MediaFile,
        Artist,
        Album,
        Track,
        Audiobook,
        Chapter,
        Torrent,
        TorrentFile,
        RssFeed,
        RssFeedItem,
        PendingFileMatch,
        IndexerConfig,
        IndexerSetting,
        IndexerSearchCache,
        User,
        InviteToken,
        RefreshToken,
        AppSetting,
        AppLog,
        VideoStream,
        AudioStream,
        Subtitle,
        MediaChapter,
        PlaybackSession,
        PlaybackProgress,
        CastDevice,
        CastSession,
        CastSetting,
        UsenetServer,
        UsenetDownload,
        ScheduleCache,
        ScheduleSyncState,
        NamingPattern,
        SourcePriorityRule,
        Notification,
        ArtworkCache,
        TorznabCategory,
    ],
    extra_mutation_types: [AuthMutations],
}

/// The GraphQL schema type
pub type LibrarianSchema = Schema<QueryRoot, MutationRoot, SubscriptionRoot>;

/// Build the GraphQL schema with all resolvers
pub fn build_schema<E>(db: Database, auth_service: E) -> LibrarianSchema
where
    E: Send + Sync + Clone + 'static,
{
    Schema::build(
        QueryRoot::default(),
        MutationRoot::default(),
        SubscriptionRoot::default(),
    )
    .data(db)
    .data(auth_service)
    .finish()
}
